#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Areas.App.Views.Shared.DisplayTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\Areas\App\Views\Shared\DisplayTemplates\Button.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/App/Views/Shared/DisplayTemplates/Button.cshtml")]
    public partial class Button : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.Button>
    {
        public Button()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n<!--ko if: ko.unwrap($type) === \"Bespoke.Sph.Domain.Button, domain.sph\" -->\r\n<d" +
"iv class=\"form-group\" data-bind=\"css: { \'selected-form-element\': isSelected }, c" +
"lick: $root.selectFormElement\">\r\n    ");


            
            #line 6 "..\..\Areas\App\Views\Shared\DisplayTemplates\Button.cshtml"
Write(Html.Partial("_DesignerContextAction"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <button data-bind=\"attr : {\'class\':CssClass},text: Label()+\' [ \' + Path() +" +
" \' ] \'\"></button>\r\n</div>\r\n<!--/ko-->\r\n");


        }
    }
}
#pragma warning restore 1591
