#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Areas.App.Views.Shared.DisplayTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\Areas\App\Views\Shared\DisplayTemplates\ChildEntityListView.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/App/Views/Shared/DisplayTemplates/ChildEntityListView.cshtml")]
    public partial class ChildEntityListView : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.ChildEntityListView>
    {
        public ChildEntityListView()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n<!--ko if:ko.unwrap($type) === \"Bespoke.Sph.Domain.ChildEntityListView, domai" +
"n.sph\" -->\r\n<div data-bind=\"css: { \'selected-form-element\': isSelected },click: " +
"$root.selectFormElement\">\r\n    ");


            
            #line 8 "..\..\Areas\App\Views\Shared\DisplayTemplates\ChildEntityListView.cshtml"
Write(Html.Partial("_DesignerContextAction"));

            
            #line default
            #line hidden
WriteLiteral(@"

    <h3 data-bind=""text: Label""></h3>
    <table class=""table table-condensed table-striped"">
        <thead>
            <tr data-bind=""foreach: ViewColumnCollection"">
                <th>
                    <a href=""#"" >
                        <span data-bind=""text:Header""></span>
                        <i class=""fa fa-check""></i>

                    </a>
                </th>
            </tr>
        </thead>
        <tbody>
");


            
            #line 24 "..\..\Areas\App\Views\Shared\DisplayTemplates\ChildEntityListView.cshtml"
             for (int i = 0; i < 5; i++)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr data-bind=\"foreach: ViewColumnCollection\">\r\n                 " +
"   <td>\r\n                        Sample\r\n                    </td>\r\n            " +
"    </tr>\r\n");


            
            #line 31 "..\..\Areas\App\Views\Shared\DisplayTemplates\ChildEntityListView.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n</div>\r\n<!--/ko-->\r\n");


        }
    }
}
#pragma warning restore 1591
