//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormElementDesigner {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormElementDesigner() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bespoke.Sph.Domain.Properties.FormElementDesigner", typeof(FormElementDesigner).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using Newtonsoft.Json
        ///@model Bespoke.Sph.Domain.BarChartItem
        ///
        ///@{
        ///    var id = Guid.NewGuid().ToString();
        ///    var series = from s in Model.ChartSeriesCollection
        ///                 select new
        ///                 {
        ///                     name = s.Header,
        ///                     data = s.Values
        ///                 };
        ///
        ///    var seriesJson = JsonConvert.SerializeObject(series);
        ///}
        ///
        ///
        ///&lt;div&gt;
        ///    &lt;div id=&quot;@id&quot;&gt;&lt;/div&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///            (function () {
        ///
        ///                $(&quot;#@id&quot;).kend [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BarChartItem {
            get {
                return ResourceManager.GetString("BarChartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;button data-bind=&quot;attr : {&apos;class&apos;:CssClass},text: Label()+&apos; [ &apos; + Path() + &apos; ] &apos;&quot;&gt;&lt;/button&gt;
        ///
        ///.
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;label class=&quot;checkbox&quot;&gt;
        ///    &lt;input type=&quot;checkbox&quot;/&gt;
        ///    &lt;span data-bind=&quot;text:&apos; [ &apos; + Path() + &apos; ] &apos;&quot;&gt;&lt;/span&gt;
        ///&lt;/label&gt;
        ///.
        /// </summary>
        internal static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3 data-bind=&quot;text: Label&quot;&gt;&lt;/h3&gt;
        ///&lt;table class=&quot;table table-condensed table-striped&quot;&gt;
        ///    &lt;thead&gt;
        ///        &lt;tr data-bind=&quot;foreach: ViewColumnCollection&quot;&gt;
        ///            &lt;th&gt;
        ///                &lt;a href=&quot;#&quot; &gt;
        ///                    &lt;span data-bind=&quot;text:Header&quot;&gt;&lt;/span&gt;
        ///                    &lt;i class=&quot;fa fa-check&quot;&gt;&lt;/i&gt;
        ///
        ///                &lt;/a&gt;
        ///            &lt;/th&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/thead&gt;
        ///    &lt;tbody&gt;
        ///        @for (int i = 0; i &lt; 5; i++)
        ///        {
        ///            &lt;tr data-bind=&quot;foreach: ViewColumnCollection&quot;&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChildEntityListView {
            get {
                return ResourceManager.GetString("ChildEntityListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;select data-bind=&quot;attr: { &apos;class&apos;: CssClass() + &apos; form-control&apos; + &apos; &apos; + Size(), &apos;title&apos;: Tooltip,&apos;placeholder&apos; : &apos; [ &apos; + Path() + &apos; ] &apos;  }&quot;&gt;
        ///    &lt;option data-bind=&quot;text:&apos; [ &apos; + Path() + &apos; ] &apos;&quot;&gt;&lt;/option&gt;
        ///&lt;/select&gt;
        ///
        ///.
        /// </summary>
        internal static string ComboBox {
            get {
                return ResourceManager.GetString("ComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input type=&quot;text&quot; data-bind=&quot;attr: { &apos;title&apos;: Tooltip, &apos;class&apos;: CssClass() + &apos; &apos; + Size() ,placeholder:&apos; [ &apos; + Path() + &apos; ] &apos;}&quot; /&gt;
        /// 
        ///.
        /// </summary>
        internal static string CurrencyElement {
            get {
                return ResourceManager.GetString("CurrencyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model Bespoke.Sph.Domain.DataGridItem
        ///@{
        ///    var index = 0;
        ///}
        ///&lt;div&gt;
        ///    &lt;table class=&quot;table table-striped&quot;&gt;
        ///        &lt;thead&gt;
        ///            &lt;tr&gt;
        ///                @foreach (var c in Model.DataGridColumnCollection)
        ///                {
        ///                    &lt;th&gt;@c.Header&lt;/th&gt;
        ///                }
        ///            &lt;/tr&gt;
        ///        &lt;/thead&gt;
        ///        &lt;tbody&gt;
        ///            @foreach (var group in Model.GetGroupHeaders())
        ///            {
        ///                &lt;tr class=&quot;alert alert-success&quot;&gt;
        ///                    &lt;td colspan=&quot;@Mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataGridItem {
            get {
                return ResourceManager.GetString("DataGridItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;input-group&quot;&gt;
        ///    &lt;input type=&quot;text&quot; data-bind=&quot;attr: { &apos;title&apos;: Tooltip, &apos;class&apos;: CssClass() + &apos; form-control &apos;,&apos;placeholder&apos;:&apos; [ &apos; + Path() + &apos; ] &apos; }&quot; /&gt;
        ///    &lt;span class=&quot;input-group-addon&quot;&gt;
        ///        &lt;span class=&quot;glyphicon glyphicon-calendar&quot;&gt;&lt;/span&gt;
        ///    &lt;/span&gt;
        ///&lt;/div&gt;
        ///    .
        /// </summary>
        internal static string DatePicker {
            get {
                return ResourceManager.GetString("DatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;input-group&quot;&gt;
        ///    &lt;input type=&quot;text&quot; data-bind=&quot;attr: { &apos;title&apos;: Tooltip, &apos;class&apos;: CssClass() + &apos; form-control &apos; + Size() ,placeholder:&apos; [ &apos; + Path() + &apos; ] &apos;}&quot; /&gt;
        ///    &lt;span class=&quot;input-group-addon glyphicon glyphicon-calendar&quot;&gt;&lt;/span&gt;
        ///    &lt;span class=&quot;input-group-addon glyphicon glyphicon-time&quot;&gt;&lt;/span&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string DateTimePicker {
            get {
                return ResourceManager.GetString("DateTimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;#&quot;&gt;
        ///    &lt;i data-bind=&quot;attr : {&apos;class&apos;:IconClass}&quot; &gt;&lt;/i&gt;
        ///    &lt;span data-bind=&quot;text:Label&quot;&gt;&lt;/span&gt;
        ///    &lt;span data-bind=&quot;text:&apos; [ &apos; + Path() + &apos; ] &apos;&quot;&gt;&lt;/span&gt;
        ///&lt;/a&gt;
        ///.
        /// </summary>
        internal static string DownloadLink {
            get {
                return ResourceManager.GetString("DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input type=&quot;email&quot; data-bind=&quot;attr: { &apos;title&apos;: Tooltip, &apos;class&apos;: CssClass() + &apos; form-control &apos; + Size() ,placeholder:&apos; [ &apos; + Path() + &apos; ] &apos;}&quot; /&gt;
        /// 
        ///
        ///
        ///.
        /// </summary>
        internal static string EmailFormElement {
            get {
                return ResourceManager.GetString("EmailFormElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;input-group&quot;&gt;
        ///
        ///    &lt;input type=&quot;text&quot; data-bind=&quot;attr: { &apos;title&apos;: Tooltip, &apos;class&apos;: CssClass() + &apos; form-control &apos;}&quot; readonly=&quot;readonly&quot; /&gt;
        ///    &lt;span class=&quot;input-group-addon&quot;&gt;
        ///    &lt;i class=&quot;fa fa-search&quot;&gt;&lt;/i&gt;
        ///    &lt;/span&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string EntityLookupElement {
            get {
                return ResourceManager.GetString("EntityLookupElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;button data-bind=&quot;attr: { &apos;class&apos;: CssClass() + &apos; form-control&apos; + &apos; &apos; + Size(), &apos;title&apos;: Tooltip }, text:&apos; [ &apos; + Path() + &apos; ] &apos;&quot;&gt;&lt;/button&gt;
        ///.
        /// </summary>
        internal static string FileUploadElement {
            get {
                return ResourceManager.GetString("FileUploadElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;label data-bind=&quot;text: Label&quot;&gt;&lt;/label&gt;
        ///.
        /// </summary>
        internal static string FormElement {
            get {
                return ResourceManager.GetString("FormElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;textarea name=&quot;html-text&quot; id=&quot;html-text&quot; data-bind=&quot;value : Text&quot; rows=&quot;10&quot; cols=&quot;30&quot; style=&quot;width:690px;min-height: 200px&quot;&gt;&lt;/textarea&gt;
        ///&lt;a href=&quot;#&quot; data-bind=&quot;click : editHtml&quot;&gt;
        ///    &lt;i class=&quot;fa fa-edit&quot;&gt;&lt;/i&gt;
        ///    Edit HTML
        ///&lt;/a&gt;
        ///
        ///.
        /// </summary>
        internal static string HtmlElement {
            get {
                return ResourceManager.GetString("HtmlElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img alt=&quot;designer&quot; src=&quot;/Images/no-image.png&quot; /&gt;
        ///&lt;span data-bind=&quot;text:&apos; [ &apos; + Path() + &apos; ] &apos;&quot; style=&quot;position: absolute; top:53px;left:60px &quot;&gt;&lt;/span&gt;
        ///.
        /// </summary>
        internal static string ImageElement {
            get {
                return ResourceManager.GetString("ImageElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model Bespoke.Sph.Domain.LabelItem
        ///
        ///&lt;div class=&quot;@Model.CssClass&quot; title=&quot;@Model.Tooltip&quot; &gt;
        ///    @Html.Raw(Model.EvaluateHtml())
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string LabelItem {
            get {
                return ResourceManager.GetString("LabelItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using Newtonsoft.Json
        ///@model Bespoke.Sph.Domain.LineChartItem
        ///@{
        ///    var id = Guid.NewGuid().ToString();
        ///    var series = from s in Model.ChartSeriesCollection
        ///        select new
        ///        {
        ///            name = s.Header,
        ///            data = s.Values
        ///        };
        ///
        ///    var seriesJson = JsonConvert.SerializeObject(series);
        ///}
        ///
        ///&lt;div&gt;
        ///    &lt;div id=&quot;@id&quot;&gt;&lt;/div&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///        (function () {
        ///
        ///            $(&quot;#@id&quot;).kendoChart({
        ///                title: {
        ///                     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LineChartItem {
            get {
                return ResourceManager.GetString("LineChartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;hr/&gt;.
        /// </summary>
        internal static string LineItem {
            get {
                return ResourceManager.GetString("LineItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input data-bind=&quot;click: $root.selectFormElement&quot; type=&quot;button&quot; class=&quot;btn btn-default&quot; value=&quot;Click to select&quot; /&gt;
        ///&lt;input data-bind=&quot;click: $root.selectFormElement,value: Label&quot; type=&quot;button&quot; class=&quot;btn btn-default pull-right&quot; /&gt;
        ///&lt;table class=&quot;table table-condensed table-striped&quot;&gt;
        ///    &lt;thead&gt;
        ///        &lt;tr data-bind=&quot;foreach: ListViewColumnCollection&quot;&gt;
        ///            &lt;th data-bind=&quot;with : Input&quot;&gt;
        ///                &lt;a href=&quot;#&quot; data-bind=&quot;click : $root.selectFormElement,css: { &apos;selected-form-element&apos;: isSelect [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input type=&quot;number&quot; data-bind=&quot;attr: { &apos;title&apos;: Tooltip, &apos;step&apos;: Step, &apos;class&apos;: CssClass() + &apos; &apos; + Size(),placeholder:&apos; [ &apos; + Path() + &apos; ] &apos; }&quot; /&gt;
        ///.
        /// </summary>
        internal static string NumberTextBox {
            get {
                return ResourceManager.GetString("NumberTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model Bespoke.Sph.Domain.PieChartItem
        ///
        ///&lt;div&gt;
        ///    &lt;div id=&quot;pie-chart&quot; &gt;&lt;/div&gt;
        ///    &lt;script&gt;
        ///        (function () {
        ///            $(&quot;#pie-chart&quot;).kendoChart({
        ///                title: {
        ///                    position: &apos;@(string.IsNullOrWhiteSpace(Model.TitlePlacement) ? &quot;bottom&quot; : Model.TitlePlacement )&apos;,
        ///                    text: &quot;@Model.EvaluateTitle()&quot;
        ///                },
        ///                legend: {
        ///                    visible: false
        ///                },
        ///                chartArea: {
        ///                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PieChartItem {
            get {
                return ResourceManager.GetString("PieChartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 data-bind=&quot;text: Label&quot;&gt;&lt;/h2&gt;
        ///&lt;div data-bind=&quot;attr : {&apos;class&apos;:CssClass},html: HelpText&quot; &gt;&lt;/div&gt;.
        /// </summary>
        internal static string SectionFormElement {
            get {
                return ResourceManager.GetString("SectionFormElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;textarea data-bind=&quot;attr: { &apos;title&apos;: Tooltip, &apos;rows&apos;: Rows, &apos;class&apos;: CssClass() + &apos; control-form &apos; + Size(),placeholder:&apos; [ &apos; + Path() + &apos; ] &apos; }&quot;&gt;&lt;/textarea&gt;.
        /// </summary>
        internal static string TextAreaElement {
            get {
                return ResourceManager.GetString("TextAreaElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input type=&quot;text&quot; data-bind=&quot;attr: { &apos;title&apos;: Tooltip, &apos;class&apos;: CssClass() + &apos; form-control &apos; + Size(),&apos;placeholder&apos; : &apos; [ &apos; + Path() + &apos; ] &apos; }&quot; /&gt;
        ///.
        /// </summary>
        internal static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input type=&quot;url&quot; data-bind=&quot;attr: { &apos;title&apos;: Tooltip, &apos;class&apos;: CssClass() + &apos; form-control &apos; + Size() ,placeholder:&apos; [ &apos; + Path() + &apos; ] &apos;}&quot; /&gt;
        ///    .
        /// </summary>
        internal static string WebsiteFormElement {
            get {
                return ResourceManager.GetString("WebsiteFormElement", resourceCulture);
            }
        }
    }
}
