[System.Environment]::SetEnvironmentVariable("RX_DEVV1_RabbitMqPassword","guest", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_RabbitMqBase","E:\project\work\rx\bin\rabbitmq_base", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_ElasticsearchIndexNumberOfShards","1", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_IisExpressExecutable","E:\project\work\rx\bin\IIS Express\iisexpress.exe", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_ElasticsearchHttpPort","9200", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_ElasticSearchJar","E:\project\work\rx\bin\elasticsearch\lib\elasticsearch-1.7.5.jar", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_ElasticsearchClusterName","cluster_WS28_DevV1", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_HOME","E:\project\work\rx\bin", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_WebPath","E:\project\work\rx\source\web\web.sph", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_RabbitMqManagementPort","15672", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_ElasticsearchIndexNumberOfReplicas","0", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_WebsitePort","4436", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_RabbitMqDirectory","E:\project\work\rx\bin\rabbitmq_server", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_LoggerWebSocketPort","50238", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_SqlLocalDbName","ProjectsV13", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_SqlConnectionString", "Data Source=(localdb)\ProjectsV13;Initial Catalog=DevV1;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_RabbitMqUserName","guest", "Process")
[System.Environment]::SetEnvironmentVariable("RX_DEVV1_ElasticsearchNodeName","node_WS28_DevV1", "Process")
[System.Environment]::SetEnvironmentVariable("RABBITMQ_BASE","E:\project\work\rx\bin\control.center\rabbitmq_base", "Process")
