#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Bespoke.Sph.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/App/Views/EntityViewDesigner/Html.cshtml")]
    public partial class _Areas_App_Views_EntityViewDesigner_Html_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_App_Views_EntityViewDesigner_Html_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\App\Views\EntityViewDesigner\Html.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n<h1");

WriteLiteral(" data-bind=\"with : entity\"");

WriteLiteral(">View Designer for <span");

WriteLiteral(" data-bind=\"text:Plural\"");

WriteLiteral("></span></h1>\r\n");

            
            #line 5 "..\..\Areas\App\Views\EntityViewDesigner\Html.cshtml"
Write(Html.Partial("_erroList"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"view-column-designer\"");

WriteLiteral(" class=\"col-lg-8 col-md-7 col-sm-10 col-xs-12\"");

WriteLiteral(">\r\n        <!-- ko compose : {model: \'viewmodels/_view.columns.designer\', activat" +
"ionData:$root.view()}-->\r\n        <!--/ko-->\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"view-properties-tab\"");

WriteLiteral(" class=\"col-lg-4 col-md-5 col-sm-2 col-xs-12\"");

WriteLiteral(">\r\n        <div>\r\n            <a");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" id=\"expand-collapse-property-tabe\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-expand\"");

WriteLiteral("></i>\r\n            </a>\r\n        </div>\r\n        <ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(" data-bind2=\"filter : {path:\'>li\'}\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" href=\"#general-ev-panel\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">General</a>\r\n            </li>\r\n    \r\n            <li>\r\n                <a");

WriteLiteral(" href=\"#route-parameters-ev-panel\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">Parameters</a>\r\n            </li>\r\n            <li>\r\n                <a");

WriteLiteral(" href=\"#cf-ev-panel\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">Formatting</a>\r\n            </li>\r\n            <li>\r\n                <a");

WriteLiteral(" href=\"#performer-ev-panel\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">Security</a>\r\n            </li>\r\n\r\n        </ul>\r\n        <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(" data-bind=\"with : view\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"general-ev-panel\"");

WriteLiteral(" class=\"tab-pane active\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 35 "..\..\Areas\App\Views\EntityViewDesigner\Html.cshtml"
           Write(Html.Partial("_general"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            \r\n       \r\n            <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"cf-ev-panel\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 40 "..\..\Areas\App\Views\EntityViewDesigner\Html.cshtml"
           Write(Html.Partial("_conditionalFormatting"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"performer-ev-panel\"");

WriteLiteral(" data-bind=\"with : Performer\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 43 "..\..\Areas\App\Views\EntityViewDesigner\Html.cshtml"
           Write(Html.Partial("_performer"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"route-parameters-ev-panel\"");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 46 "..\..\Areas\App\Views\EntityViewDesigner\Html.cshtml"
           Write(Html.Partial("_parameters"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
