#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Areas.App.Views.EntityFormDesigner
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\Areas\App\Views\EntityFormDesigner\_Toolbox.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\App\Views\EntityFormDesigner\_Toolbox.cshtml"
    using Bespoke.Sph.Domain;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/App/Views/EntityFormDesigner/_Toolbox.cshtml")]
    public partial class Toolbox : System.Web.Mvc.WebViewPage<Bespoke.Sph.Web.ViewModels.TemplateFormViewModel>
    {
        public Toolbox()
        {
        }
        public override void Execute()
        {



WriteLiteral("\r\n<div id=\"form-designer-toolbox\" data-path=\"Areas\\App\\Views\\EntityFormDesigner\\_" +
"Toolbox.cshtml\">\r\n    <ul class=\"nav nav-tabs\" data-bind2=\"filter : {path:\'>li\'}" +
"\">\r\n        <li class=\"active\">\r\n            <a href=\"#form-general2\" data-toggl" +
"e=\"tab\">General</a>\r\n        </li>\r\n        <li>\r\n            <a href=\"#add-fiel" +
"d\" data-toggle=\"tab\">Add a field</a>\r\n        </li>\r\n        <li>\r\n            <" +
"a href=\"#fields-settings\" data-toggle=\"tab\">Properties</a>\r\n        </li>\r\n     " +
"   <li>\r\n            <a href=\"#fields-validation\" data-toggle=\"tab\">Validations<" +
"/a>\r\n        </li>\r\n\r\n        <li>\r\n            <a href=\"#business-rules\" data-t" +
"oggle=\"tab\">Business Rules</a>\r\n        </li>\r\n\r\n    </ul>\r\n    <div class=\"tab-" +
"content\">\r\n        <div id=\"form-general2\" class=\"tab-pane active\" data-bind=\"wi" +
"th : form\">\r\n            <form role=\"form\">\r\n                <div class=\"form-gr" +
"oup\">\r\n                    <label>Name</label>\r\n                    <input class" +
"=\"form-control\" data-bind=\"value: Name\" id=\"form-design-name\" type=\"text\" name=\"" +
"FormDesign.Name\" />\r\n                </div>\r\n                <div class=\"form-gr" +
"oup\">\r\n                    <label for=\"form-design-operation\">Operation</label>\r" +
"\n                    <select class=\"form-control\" data-bind=\"options :$root.oper" +
"ationsOption, \r\n                            optionsCaption :\'[Default - No Opera" +
"tion]\',\r\n                            value: Operation\" id=\"form-design-operation" +
"\" name=\"FormDesign.Operation\">\r\n                        \r\n                    </" +
"select>\r\n                </div>\r\n                <div class=\"form-group\">\r\n     " +
"               <label>Note</label>\r\n                    <input class=\"form-contr" +
"ol\" data-bind=\"value: Note\" id=\"form-design-Description\" type=\"text\" name=\"FormD" +
"esign.Description\" />\r\n                </div>\r\n                <div class=\"form-" +
"group\">\r\n                    <label for=\"form-design-icon-class\">Icon class</lab" +
"el>\r\n                    <br/>\r\n                    <i data-bind=\"iconPicker: Ic" +
"onClass, attr:{\'class\':IconClass() + \' fa-2x\' }\"  id=\"form-design-icon-class\"></" +
"i>\r\n\r\n                </div>\r\n                <div class=\"form-group\">\r\n        " +
"            <label>Route</label>\r\n                    <input class=\"form-control" +
"\" data-bind=\"value: Route\" id=\"form-design-Route\" type=\"text\" name=\"FormDesign.R" +
"oute\" />\r\n                </div>\r\n\r\n                <div class=\"form-group\">\r\n  " +
"                  <label>\r\n                        <input data-bind=\"checked: Is" +
"Default\" id=\"form-design-isdefault\" type=\"checkbox\" name=\"FormDesign.IsDefault\" " +
"/>\r\n                        Is default form\r\n                    </label>\r\n     " +
"           </div>\r\n                <div class=\"form-group\">\r\n                   " +
" <label>\r\n                        <input data-bind=\"checked: IsAllowedNewItem\" i" +
"d=\"form-design-is-allow-new\" type=\"checkbox\" name=\"FormDesign.IsAllowedNewItem\" " +
"/>\r\n                        Allow new item\r\n                    </label>\r\n      " +
"          </div>\r\n                <div class=\"form-group\">\r\n                    " +
"<label>\r\n                        <input data-bind=\"checked: IsRemoveAvailable\" i" +
"d=\"form-design-is-remove-item\" type=\"checkbox\" name=\"FormDesign.IsRemoveAvailabl" +
"e\" />\r\n                        Allow remove item\r\n                    </label>\r\n" +
"                </div>\r\n                <div class=\"form-group\">\r\n              " +
"      <label>\r\n                        <input data-bind=\"checked: IsEmailAvailab" +
"le\" id=\"form-design-isemail\" type=\"checkbox\" name=\"FormDesign.IsEmailAvailable\" " +
"/>\r\n                        Allow Email\r\n                    </label>\r\n         " +
"       </div>\r\n\r\n                <div class=\"form-group\">\r\n                    <" +
"label>\r\n                        <input data-bind=\"checked: IsPrintAvailable\" id=" +
"\"form-design-isprint\" type=\"checkbox\" name=\"FormDesign.IsPrintAvailable\" />\r\n   " +
"                     Allow Print\r\n                    </label>\r\n                " +
"</div>\r\n                <div class=\"form-group\">\r\n                    <label>\r\n " +
"                       <input data-bind=\"checked: IsWatchAvailable\" id=\"form-des" +
"ign-iswatch\" type=\"checkbox\" name=\"FormDesign.IsWatchAvailable\" />\r\n            " +
"            Allow Watch\r\n                    </label>\r\n                </div>\r\n " +
"               <div class=\"form-group\">\r\n                    <label>\r\n          " +
"              <input data-bind=\"checked: IsAuditTrailAvailable\" id=\"form-design-" +
"IsAuditTrailAvailable\" type=\"checkbox\" name=\"FormDesign.IsAuditTrailAvailable\" /" +
">\r\n                        Audit trail\r\n                    </label>\r\n          " +
"      </div>\r\n\r\n                <!-- ko with : FormDesign -->\r\n\r\n\r\n             " +
"   <div class=\"form-group\">\r\n                    <a href=\"#label-cols\" data-togg" +
"le=\"collapse\"><i class=\"fa fa-chevron-down\"></i>Label columns span</a>\r\n        " +
"        </div>\r\n                <div id=\"label-cols\" class=\"form-group collapse\"" +
">\r\n                    <div class=\"form-group\">\r\n                        <label>" +
"Label Col Large</label>\r\n                        <input class=\"form-control\" dat" +
"a-bind=\"value: LabelColLg\" id=\"form-design-LabelColLg\" type=\"number\" name=\"FormD" +
"esign.LabelColLg\" />\r\n                    </div>\r\n                    <div class" +
"=\"form-group\">\r\n                        <label>Label Col Medium</label>\r\n       " +
"                 <input class=\"form-control\" data-bind=\"value: LabelColMd\" id=\"f" +
"orm-design-LabelColMd\" type=\"number\" name=\"FormDesign.LabelColMd\" />\r\n          " +
"          </div>\r\n                    <div class=\"form-group\">\r\n                " +
"        <label>Label Col Small</label>\r\n                        <input class=\"fo" +
"rm-control\" data-bind=\"value: LabelColSm\" id=\"form-design-LabelColSm\" type=\"numb" +
"er\" name=\"FormDesign.LabelColSm\" />\r\n                    </div>\r\n               " +
"     <div class=\"form-group\">\r\n                        <label>Label Col x-small<" +
"/label>\r\n                        <input class=\"form-control\" data-bind=\"value: L" +
"abelColXs\" id=\"form-design-LabelColXs\" type=\"number\" name=\"FormDesign.LabelColXs" +
"\" />\r\n                    </div>\r\n                </div>\r\n\r\n                <div" +
" class=\"form-group\">\r\n                    <a href=\"#input-cols\" data-toggle=\"col" +
"lapse\"><i class=\"fa fa-chevron-down\"></i>Input columns span</a>\r\n               " +
" </div>\r\n                <div id=\"input-cols\" class=\"collapse form-group\">\r\n    " +
"                <div class=\"form-group\">\r\n                        <label>Input C" +
"ol Large</label>\r\n                        <input class=\"form-control\" data-bind=" +
"\"value: InputColLg\" id=\"form-design-InputColLg\" type=\"number\" name=\"FormDesign.I" +
"nputColLg\" />\r\n                    </div>\r\n                    <div class=\"form-" +
"group\">\r\n                        <label>Input Col Medium</label>\r\n              " +
"          <input class=\"form-control\" data-bind=\"value: InputColMd\" id=\"form-des" +
"ign-InputColMd\" type=\"number\" name=\"FormDesign.InputColMd\" />\r\n                 " +
"   </div>\r\n                    <div class=\"form-group\">\r\n                       " +
" <label>Input Col Small</label>\r\n                        <input class=\"form-cont" +
"rol\" data-bind=\"value: InputColSm\" id=\"form-design-InputColSm\" type=\"number\" nam" +
"e=\"FormDesign.InputColSm\" />\r\n                    </div>\r\n                    <d" +
"iv class=\"form-group\">\r\n                        <label>Input Col x-small</label>" +
"\r\n                        <input class=\"form-control\" data-bind=\"value: InputCol" +
"Xs\" id=\"form-design-InputColXs\" type=\"number\" name=\"FormDesign.InputColXs\" />\r\n " +
"                   </div>\r\n\r\n                </div>\r\n\r\n\r\n                <!-- /k" +
"o -->\r\n\r\n            </form>\r\n        </div>\r\n        <div id=\"add-field\" class=" +
"\"tab-pane\">\r\n            <ul class=\"nav\" data-bind=\"foreach: formElements\">\r\n   " +
"             <li>\r\n                    <a class=\"btn btn-default\" href=\"#add-fie" +
"ld\" data-bind=\"attr : {title:Tooltip}\">\r\n                        <i data-bind=\"a" +
"ttr: { \'class\': CssClass }\" class=\"pull-left\"></i>\r\n                        <!--" +
" ko text: Name -->\r\n                        <!-- /ko-->\r\n                    </a" +
">\r\n                </li>\r\n            </ul>\r\n        </div>\r\n\r\n        <div id=\"" +
"fields-settings\" class=\"tab-pane\" data-bind=\"with: selectedFormElement\">\r\n      " +
"      <form role=\"form\">\r\n                <div class=\"form-group\">\r\n            " +
"        <label for=\"form-element-label\">Label</label>\r\n                    <inpu" +
"t class=\"form-control\" data-bind=\"value: Label, valueUpdate: \'keyup\'\" id=\"form-e" +
"lement-label\" type=\"text\" name=\"Label\" />\r\n                </div>\r\n\r\n           " +
"     <div class=\"form-group\">\r\n                    <label for=\"form-element-path" +
"\">Path</label>\r\n                    ");



WriteLiteral("\r\n                    <input class=\"form-control\" pattern=\"^[A-Za-z_][A-Za-z0-9_." +
"]*$\" data-bind=\"value: Path, entityTypeaheadPath : $root.entity().EntityDefiniti" +
"onId()\" id=\"form-element-path\" type=\"text\" name=\"Path\" />\r\n                </div" +
">\r\n                <div class=\"form-group\" style=\"padding-top: 25px\">\r\n         " +
"           <label for=\"use-display-template\">\r\n                        Use displ" +
"ay template\r\n                    </label>\r\n                    <input data-bind=" +
"\"checked: UseDisplayTemplate\" id=\"use-display-template\" type=\"checkbox\" name=\"Us" +
"eDisplayTemplate\" />\r\n                </div>\r\n                <div class=\"form-g" +
"roup\">\r\n                    <a href=\"#toolbox-more-settings\" data-toggle=\"collap" +
"se\"><i class=\"fa fa-chevron-down\"></i>More settings</a>\r\n                </div>\r" +
"\n                <div id=\"toolbox-more-settings\" class=\"collapse\">\r\n            " +
"        <div class=\"form-group\">\r\n                        <label for=\"form-eleme" +
"nt-tooltip\">Tooltip</label>\r\n                        <input class=\"form-control\"" +
" data-bind=\"value: Tooltip\" id=\"form-element-tooltip\" type=\"text\" name=\"Tooltip\"" +
" />\r\n                    </div>\r\n\r\n                    <div class=\"form-group\">\r" +
"\n                        <label for=\"form-element-help-text\">Help</label>\r\n     " +
"                   <input class=\"form-control\" data-bind=\"value: HelpText, value" +
"Update: \'keyup\'\" id=\"form-element-help-text\" type=\"text\" name=\"HelpText\" />\r\n   " +
"                 </div>\r\n\r\n\r\n                    <div class=\"form-group\">\r\n     " +
"                   <label for=\"form-element-css-class\">Css class</label>\r\n      " +
"                  <input data-bind=\"cssAutoComplete: CssClass\" id=\"form-element-" +
"css-class\" type=\"text\" name=\"CssClass\" />\r\n                    </div>\r\n\r\n       " +
"             <div class=\"form-group\">\r\n                        <label for=\"form-" +
"element-visible\">Visible</label>\r\n                        <input class=\"form-con" +
"trol\" data-bind=\"value: Visible\" id=\"form-element-visible\" type=\"text\" name=\"Vis" +
"ible\" />\r\n                    </div>\r\n                    <div class=\"form-group" +
"\">\r\n                        <label for=\"form-element-enable\">Enable</label>\r\n   " +
"                     <input class=\"form-control\" data-bind=\"value: Enable\" id=\"f" +
"orm-element-enable\" type=\"text\" name=\"Enable\" />\r\n                    </div>\r\n\r\n" +
"\r\n                    <div class=\"form-group\">\r\n                        <label f" +
"or=\"form-element-elementId\">Id</label>\r\n                        <input class=\"fo" +
"rm-control\" data-bind=\"value: ElementId\" id=\"form-element-elementId\" type=\"text\"" +
" name=\"ElementId\" />\r\n                    </div>\r\n\r\n\r\n                </div>\r\n\r\n" +
"                <div class=\"form-group\">\r\n                    <a href=\"#toolbox-" +
"advanced-settings\" data-toggle=\"collapse\">\r\n                        <i class=\"fa" +
" fa-chevron-down\"></i>\r\n                        Advanced settings\r\n             " +
"       </a>\r\n                </div>\r\n                <div id=\"toolbox-advanced-s" +
"ettings\" class=\"collapse\">\r\n");


            
            #line 227 "..\..\Areas\App\Views\EntityFormDesigner\_Toolbox.cshtml"
                      
                        var types = new[]
                        {
                            typeof(TextBox),
                            typeof(ComboBox),
                            typeof(Button),
                            typeof(DownloadLink),
                            typeof(ImageElement),
                            typeof(ListView)
                        };
                    

            
            #line default
            #line hidden

            
            #line 238 "..\..\Areas\App\Views\EntityFormDesigner\_Toolbox.cshtml"
                     foreach (var fe in Model.FormElements.Where(t => types.Contains(t.GetType())))
                    {
                        FormElement fe1 = fe;
                        
            
            #line default
            #line hidden
            
            #line 241 "..\..\Areas\App\Views\EntityFormDesigner\_Toolbox.cshtml"
                   Write(Html.EditorFor(m => fe1));

            
            #line default
            #line hidden
            
            #line 241 "..\..\Areas\App\Views\EntityFormDesigner\_Toolbox.cshtml"
                                                 
                    }

            
            #line default
            #line hidden
WriteLiteral(@"                </div>

                <button data-bind=""click: $root.removeFormElement"" class=""btn btn-warning"" title=""remove this element"">Remove</button>
                <!-- END OF EDITOR TOOLBOX -->
            </form>

        </div>

        <div id=""fields-validation"" class=""tab-pane"" data-bind=""with : selectedFormElement"">
            ");


            
            #line 252 "..\..\Areas\App\Views\EntityFormDesigner\_Toolbox.cshtml"
       Write(Html.Partial("_ValidationSetting"));

            
            #line default
            #line hidden
WriteLiteral(@"
        </div>

        <div id=""business-rules"" class=""tab-pane"">
            <span>Apply these business rules to the form</span>
            <ul data-bind=""foreach :entity().BusinessRuleCollection"" class=""nav"">
                <li>
                    <label>
                        <input type=""checkbox"" data-bind=""checked : $root.form().Rules, value: Name"" />
                        <!-- ko text : Name -->
                        <!-- /ko -->

                    </label>
                </li>
            </ul>
        </div>

    </div>
</div>
");


        }
    }
}
#pragma warning restore 1591
