#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Areas.App.Views.EntityFormDesigner
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\Areas\App\Views\EntityFormDesigner\_Toolbox.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\App\Views\EntityFormDesigner\_Toolbox.cshtml"
    using Bespoke.Sph.Domain;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/App/Views/EntityFormDesigner/_Toolbox.cshtml")]
    public partial class Toolbox : System.Web.Mvc.WebViewPage<Bespoke.Sph.Web.ViewModels.TemplateFormViewModel>
    {
        public Toolbox()
        {
        }
        public override void Execute()
        {



WriteLiteral("\r\n<div id=\"form-designer-toolbox\" data-path=\"Areas\\App\\Views\\EntityFormDesigner\\_" +
"Toolbox.cshtml\">\r\n    <ul class=\"nav nav-tabs\" data-bind2=\"filter : {path:\'>li\'}" +
"\">\r\n        <li class=\"active\">\r\n            <a href=\"#form-general2\" data-toggl" +
"e=\"tab\">General</a>\r\n        </li>\r\n        <li>\r\n            <a href=\"#add-fiel" +
"d\" data-toggle=\"tab\">Add a field</a>\r\n        </li>\r\n        <li>\r\n            <" +
"a href=\"#fields-settings\" data-toggle=\"tab\">Properties</a>\r\n        </li>\r\n     " +
"   <li>\r\n            <a href=\"#fields-validation\" data-toggle=\"tab\">Validations<" +
"/a>\r\n        </li>\r\n\r\n        <li>\r\n            <a href=\"#business-rules\" data-t" +
"oggle=\"tab\">Business Rules</a>\r\n        </li>\r\n\r\n    </ul>\r\n    <div class=\"tab-" +
"content\">\r\n        <div id=\"form-general2\" class=\"tab-pane active\" data-bind=\"wi" +
"th : form\">\r\n            <form role=\"form\">\r\n                <div class=\"form-gr" +
"oup\">\r\n                    <label>Name</label>\r\n                    <input class" +
"=\"form-control\" data-bind=\"value: Name\" id=\"form-design-name\" type=\"text\" name=\"" +
"FormDesign.Name\" />\r\n                </div>\r\n                <div class=\"form-gr" +
"oup\">\r\n                    <label>Route</label>\r\n                    <input clas" +
"s=\"form-control\" data-bind=\"value: Route\" id=\"form-design-Route\" type=\"text\" nam" +
"e=\"FormDesign.Route\" />\r\n                </div>\r\n                <div class=\"for" +
"m-group\">\r\n                    <label for=\"form-design-operation\">Operation</lab" +
"el>\r\n                    <select class=\"form-control\" data-bind=\"options :$root." +
"operationsOption,\r\n                            optionsCaption :\'[Default - No Op" +
"eration]\',\r\n                            value: Operation\" id=\"form-design-operat" +
"ion\" name=\"FormDesign.Operation\"></select>\r\n                </div>\r\n            " +
"    <div class=\"form-group\">\r\n                    <label for=\"form-design-icon-c" +
"lass\">Icon class</label>\r\n                    <br />\r\n                    <i dat" +
"a-bind=\"iconPicker: IconClass, attr:{\'class\':IconClass() + \' fa-2x\' }\" id=\"form-" +
"design-icon-class\"></i>\r\n\r\n                </div>\r\n                <div class=\"f" +
"orm-group\">\r\n                    <label>Note</label>\r\n                    <input" +
" class=\"form-control\" data-bind=\"value: Note\" id=\"form-design-Description\" type=" +
"\"text\" name=\"FormDesign.Description\" />\r\n                </div>\r\n\r\n             " +
"   <div class=\"form-group\">\r\n                    <label>\r\n                      " +
"  <input data-bind=\"checked: IsDefault\" id=\"form-design-isdefault\" type=\"checkbo" +
"x\" name=\"FormDesign.IsDefault\" />\r\n                        Is default form\r\n    " +
"                </label>\r\n                </div>\r\n                <div class=\"fo" +
"rm-group\">\r\n                    <label>\r\n                        <input data-bin" +
"d=\"checked: IsAllowedNewItem\" id=\"form-design-is-allow-new\" type=\"checkbox\" name" +
"=\"FormDesign.IsAllowedNewItem\" />\r\n                        Allow new item\r\n     " +
"               </label>\r\n                </div>\r\n                <div class=\"for" +
"m-group\">\r\n                    <label>\r\n                        <input data-bind" +
"=\"checked: IsRemoveAvailable\" id=\"form-design-is-remove-item\" type=\"checkbox\" na" +
"me=\"FormDesign.IsRemoveAvailable\" />\r\n                        Allow remove item\r" +
"\n                    </label>\r\n                </div>\r\n                <div clas" +
"s=\"form-group\">\r\n                    <label>\r\n                        <input dat" +
"a-bind=\"checked: IsEmailAvailable\" id=\"form-design-isemail\" type=\"checkbox\" name" +
"=\"FormDesign.IsEmailAvailable\" />\r\n                        Allow Email\r\n        " +
"            </label>\r\n                </div>\r\n\r\n                <div class=\"form" +
"-group\">\r\n                    <label>\r\n                        <input data-bind=" +
"\"checked: IsPrintAvailable\" id=\"form-design-isprint\" type=\"checkbox\" name=\"FormD" +
"esign.IsPrintAvailable\" />\r\n                        Allow Print\r\n               " +
"     </label>\r\n                </div>\r\n                <div class=\"form-group\">\r" +
"\n                    <label>\r\n                        <input data-bind=\"checked:" +
" IsWatchAvailable\" id=\"form-design-iswatch\" type=\"checkbox\" name=\"FormDesign.IsW" +
"atchAvailable\" />\r\n                        Allow Watch\r\n                    </la" +
"bel>\r\n                </div>\r\n                <div class=\"form-group\">\r\n        " +
"            <label>\r\n                        <input data-bind=\"checked: IsAuditT" +
"railAvailable\" id=\"form-design-IsAuditTrailAvailable\" type=\"checkbox\" name=\"Form" +
"Design.IsAuditTrailAvailable\" />\r\n                        Audit trail\r\n         " +
"           </label>\r\n                </div>\r\n\r\n                <!-- ko with : Fo" +
"rmDesign -->\r\n\r\n\r\n                <div class=\"form-group\">\r\n                    " +
"<a href=\"#label-cols\" data-toggle=\"collapse\"><i class=\"fa fa-chevron-down\"></i>L" +
"abel columns span</a>\r\n                </div>\r\n                <div id=\"label-co" +
"ls\" class=\"form-group collapse\">\r\n                    <div class=\"form-group\">\r\n" +
"                        <label>Label Col Large</label>\r\n                        " +
"<input class=\"form-control\" data-bind=\"value: LabelColLg\" id=\"form-design-LabelC" +
"olLg\" type=\"number\" name=\"FormDesign.LabelColLg\" />\r\n                    </div>\r" +
"\n                    <div class=\"form-group\">\r\n                        <label>La" +
"bel Col Medium</label>\r\n                        <input class=\"form-control\" data" +
"-bind=\"value: LabelColMd\" id=\"form-design-LabelColMd\" type=\"number\" name=\"FormDe" +
"sign.LabelColMd\" />\r\n                    </div>\r\n                    <div class=" +
"\"form-group\">\r\n                        <label>Label Col Small</label>\r\n         " +
"               <input class=\"form-control\" data-bind=\"value: LabelColSm\" id=\"for" +
"m-design-LabelColSm\" type=\"number\" name=\"FormDesign.LabelColSm\" />\r\n            " +
"        </div>\r\n                    <div class=\"form-group\">\r\n                  " +
"      <label>Label Col x-small</label>\r\n                        <input class=\"fo" +
"rm-control\" data-bind=\"value: LabelColXs\" id=\"form-design-LabelColXs\" type=\"numb" +
"er\" name=\"FormDesign.LabelColXs\" />\r\n                    </div>\r\n               " +
" </div>\r\n\r\n                <div class=\"form-group\">\r\n                    <a href" +
"=\"#input-cols\" data-toggle=\"collapse\"><i class=\"fa fa-chevron-down\"></i>Input co" +
"lumns span</a>\r\n                </div>\r\n                <div id=\"input-cols\" cla" +
"ss=\"collapse form-group\">\r\n                    <div class=\"form-group\">\r\n       " +
"                 <label>Input Col Large</label>\r\n                        <input " +
"class=\"form-control\" data-bind=\"value: InputColLg\" id=\"form-design-InputColLg\" t" +
"ype=\"number\" name=\"FormDesign.InputColLg\" />\r\n                    </div>\r\n      " +
"              <div class=\"form-group\">\r\n                        <label>Input Col" +
" Medium</label>\r\n                        <input class=\"form-control\" data-bind=\"" +
"value: InputColMd\" id=\"form-design-InputColMd\" type=\"number\" name=\"FormDesign.In" +
"putColMd\" />\r\n                    </div>\r\n                    <div class=\"form-g" +
"roup\">\r\n                        <label>Input Col Small</label>\r\n                " +
"        <input class=\"form-control\" data-bind=\"value: InputColSm\" id=\"form-desig" +
"n-InputColSm\" type=\"number\" name=\"FormDesign.InputColSm\" />\r\n                   " +
" </div>\r\n                    <div class=\"form-group\">\r\n                        <" +
"label>Input Col x-small</label>\r\n                        <input class=\"form-cont" +
"rol\" data-bind=\"value: InputColXs\" id=\"form-design-InputColXs\" type=\"number\" nam" +
"e=\"FormDesign.InputColXs\" />\r\n                    </div>\r\n\r\n                </di" +
"v>\r\n\r\n\r\n                <!-- /ko -->\r\n\r\n            </form>\r\n        </div>\r\n   " +
"     <div id=\"add-field\" class=\"tab-pane\">\r\n            <ul class=\"nav\" data-bin" +
"d=\"foreach: formElements\">\r\n                <li>\r\n                    <a class=\"" +
"btn btn-default\" href=\"#add-field\" data-bind=\"attr : {title:Tooltip}\">\r\n        " +
"                <i data-bind=\"attr: { \'class\': ToolboxIconClass }\" class=\"pull-l" +
"eft\"></i>\r\n                        <!-- ko text: Name -->\r\n                     " +
"   <!-- /ko-->\r\n                    </a>\r\n                </li>\r\n            </u" +
"l>\r\n        </div>\r\n\r\n        <div id=\"fields-settings\" class=\"tab-pane\" data-bi" +
"nd=\"with: selectedFormElement\">\r\n            <form role=\"form\">\r\n               " +
" <div class=\"form-group\">\r\n                    <label for=\"form-element-label\">L" +
"abel</label>\r\n                    <input class=\"form-control\" data-bind=\"value: " +
"Label, valueUpdate: \'keyup\'\" id=\"form-element-label\" type=\"text\" name=\"Label\" />" +
"\r\n                </div>\r\n\r\n                <div class=\"form-group\">\r\n          " +
"          <label for=\"form-element-path\">Path</label>\r\n                    ");



WriteLiteral("\r\n                    <input class=\"form-control\" pattern=\"^[A-Za-z_][A-Za-z0-9_." +
"]*$\" data-bind=\"value: Path, entityTypeaheadPath : $root.entity().EntityDefiniti" +
"onId()\" id=\"form-element-path\" type=\"text\" name=\"Path\" />\r\n                </div" +
">\r\n                <div class=\"form-group\" style=\"padding-top: 25px\">\r\n         " +
"           <label for=\"use-display-template\">\r\n                        Use displ" +
"ay template\r\n                    </label>\r\n                    <input data-bind=" +
"\"checked: UseDisplayTemplate\" id=\"use-display-template\" type=\"checkbox\" name=\"Us" +
"eDisplayTemplate\" />\r\n                </div>\r\n                <div class=\"form-g" +
"roup\">\r\n                    <a href=\"#toolbox-more-settings\" data-toggle=\"collap" +
"se\"><i class=\"fa fa-chevron-down\"></i>More settings</a>\r\n                </div>\r" +
"\n                <div id=\"toolbox-more-settings\" class=\"collapse\">\r\n            " +
"        <div class=\"form-group\">\r\n                        <label for=\"form-eleme" +
"nt-tooltip\">Tooltip</label>\r\n                        <input class=\"form-control\"" +
" data-bind=\"value: Tooltip\" id=\"form-element-tooltip\" type=\"text\" name=\"Tooltip\"" +
" />\r\n                    </div>\r\n\r\n                    <div class=\"form-group\">\r" +
"\n                        <label for=\"form-element-help-text\">Help</label>\r\n     " +
"                   <input class=\"form-control\" data-bind=\"value: HelpText, value" +
"Update: \'keyup\'\" id=\"form-element-help-text\" type=\"text\" name=\"HelpText\" />\r\n   " +
"                 </div>\r\n\r\n\r\n                    <div class=\"form-group\">\r\n     " +
"                   <label for=\"fe-css-class\">Css class</label>\r\n                " +
"        <input data-bind=\"value: CssClass\" id=\"fe-css-class\" type=\"text\" name=\"C" +
"ssClass\" />\r\n                    </div>\r\n\r\n                    <div class=\"form-" +
"group\">\r\n                        <label for=\"form-element-visible\">Visible</labe" +
"l>\r\n                        <input class=\"form-control\" data-bind=\"value: Visibl" +
"e\" id=\"form-element-visible\" type=\"text\" name=\"Visible\" />\r\n                    " +
"</div>\r\n                    <div class=\"form-group\">\r\n                        <l" +
"abel for=\"form-element-enable\">Enable</label>\r\n                        <input cl" +
"ass=\"form-control\" data-bind=\"value: Enable\" id=\"form-element-enable\" type=\"text" +
"\" name=\"Enable\" />\r\n                    </div>\r\n\r\n\r\n                    <div cla" +
"ss=\"form-group\">\r\n                        <label for=\"form-element-elementId\">Id" +
"</label>\r\n                        <input class=\"form-control\" data-bind=\"value: " +
"ElementId\" id=\"form-element-elementId\" type=\"text\" name=\"ElementId\" />\r\n        " +
"            </div>\r\n\r\n                </div>\r\n\r\n                <div class=\"form" +
"-group\">\r\n                    <a href=\"#toolbox-advanced-settings\" data-toggle=\"" +
"collapse\">\r\n                        <i class=\"fa fa-chevron-down\"></i>\r\n        " +
"                Advanced settings\r\n                    </a>\r\n                </d" +
"iv>\r\n                <div id=\"toolbox-advanced-settings\" class=\"collapse\">\r\n");


            
            #line 224 "..\..\Areas\App\Views\EntityFormDesigner\_Toolbox.cshtml"
                      
                        var types = new[]
                        {
                            typeof(TextBox),
                            typeof(ComboBox),
                            typeof(Button),
                            typeof(DownloadLink),
                            typeof(ImageElement),
                            typeof(ChildEntityListView),
                            typeof(EntityLookupElement),
                            typeof(ListView)
                        };
                    

            
            #line default
            #line hidden

            
            #line 237 "..\..\Areas\App\Views\EntityFormDesigner\_Toolbox.cshtml"
                     foreach (var fe in Model.FormElements.Where(t => types.Contains(t.GetType())))
                    {
                        FormElement fe1 = fe;
                        
            
            #line default
            #line hidden
            
            #line 240 "..\..\Areas\App\Views\EntityFormDesigner\_Toolbox.cshtml"
                   Write(Html.EditorFor(m => fe1));

            
            #line default
            #line hidden
            
            #line 240 "..\..\Areas\App\Views\EntityFormDesigner\_Toolbox.cshtml"
                                                 
                    }

            
            #line default
            #line hidden
WriteLiteral(@"                </div>

                <button data-bind=""click: $root.removeFormElement"" class=""btn btn-warning"" title=""remove this element"">Remove</button>
                <!-- END OF EDITOR TOOLBOX -->
            </form>

        </div>

        <div id=""fields-validation"" class=""tab-pane"" data-bind=""with : selectedFormElement"">
            ");


            
            #line 251 "..\..\Areas\App\Views\EntityFormDesigner\_Toolbox.cshtml"
       Write(Html.Partial("_ValidationSetting"));

            
            #line default
            #line hidden
WriteLiteral(@"
        </div>

        <div id=""business-rules"" class=""tab-pane"">
            <span>Apply these business rules to the form</span>
            <ul data-bind=""foreach :entity().BusinessRuleCollection"" class=""nav"">
                <li>
                    <label>
                        <input type=""checkbox"" data-bind=""checked : $root.form().Rules, value: Name"" />
                        <!-- ko text : Name -->
                        <!-- /ko -->

                    </label>
                </li>
            </ul>
        </div>

    </div>
</div>
");


        }
    }
}
#pragma warning restore 1591
