#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sph/Views/Workflow/EditorTemplates/ComboBox.cshtml")]
    public partial class _Areas_Sph_Views_Workflow_EditorTemplates_ComboBox_cshtml_ : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.ComboBox>
    {
        public _Areas_Sph_Views_Workflow_EditorTemplates_ComboBox_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" data-bind=\"visible:");

            
            #line 2 "..\..\Areas\Sph\Views\Workflow\EditorTemplates\ComboBox.cshtml"
                                      Write(Html.Raw(Model.Visible));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n    <label");

WriteAttribute("for", Tuple.Create(" for=\"", 117), Tuple.Create("\"", 139)
            
            #line 3 "..\..\Areas\Sph\Views\Workflow\EditorTemplates\ComboBox.cshtml"
, Tuple.Create(Tuple.Create("", 123), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 123), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 140), Tuple.Create("\"", 168)
            
            #line 3 "..\..\Areas\Sph\Views\Workflow\EditorTemplates\ComboBox.cshtml"
, Tuple.Create(Tuple.Create("", 148), Tuple.Create<System.Object, System.Int32>(Model.LabelCssClass
            
            #line default
            #line hidden
, 148), false)
);

WriteLiteral(">");

            
            #line 3 "..\..\Areas\Sph\Views\Workflow\EditorTemplates\ComboBox.cshtml"
                                                          Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 200), Tuple.Create("\"", 233)
            
            #line 4 "..\..\Areas\Sph\Views\Workflow\EditorTemplates\ComboBox.cshtml"
, Tuple.Create(Tuple.Create("", 208), Tuple.Create<System.Object, System.Int32>(Model.InputPanelCssClass
            
            #line default
            #line hidden
, 208), false)
);

WriteLiteral(">\r\n        <select");

WriteLiteral(" data-bind=\"");

            
            #line 5 "..\..\Areas\Sph\Views\Workflow\EditorTemplates\ComboBox.cshtml"
                       Write(Html.Raw(Model.GetKnockoutBindingExpression()));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 314), Tuple.Create("\"", 335)
            
            #line 5 "..\..\Areas\Sph\Views\Workflow\EditorTemplates\ComboBox.cshtml"
   , Tuple.Create(Tuple.Create("", 319), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 319), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 336), Tuple.Create("\"", 356)
            
            #line 5 "..\..\Areas\Sph\Views\Workflow\EditorTemplates\ComboBox.cshtml"
                            , Tuple.Create(Tuple.Create("", 343), Tuple.Create<System.Object, System.Int32>(Model.Path
            
            #line default
            #line hidden
, 343), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 357), Tuple.Create("\"", 413)
            
            #line 5 "..\..\Areas\Sph\Views\Workflow\EditorTemplates\ComboBox.cshtml"
                                                  , Tuple.Create(Tuple.Create("", 365), Tuple.Create<System.Object, System.Int32>(Model.CssClass + " "+ Model.Size
            
            #line default
            #line hidden
, 365), false)
, Tuple.Create(Tuple.Create(" ", 400), Tuple.Create("form-control", 401), true)
);

WriteLiteral(">\r\n");

            
            #line 6 "..\..\Areas\Sph\Views\Workflow\EditorTemplates\ComboBox.cshtml"
            
            
            #line default
            #line hidden
            
            #line 6 "..\..\Areas\Sph\Views\Workflow\EditorTemplates\ComboBox.cshtml"
             foreach (var op in Model.ComboBoxItemCollection)
            {

            
            #line default
            #line hidden
WriteLiteral("                <option");

WriteAttribute("value", Tuple.Create(" value=\"", 518), Tuple.Create("\"", 535)
            
            #line 8 "..\..\Areas\Sph\Views\Workflow\EditorTemplates\ComboBox.cshtml"
, Tuple.Create(Tuple.Create("", 526), Tuple.Create<System.Object, System.Int32>(op.Value
            
            #line default
            #line hidden
, 526), false)
);

WriteLiteral(">");

            
            #line 8 "..\..\Areas\Sph\Views\Workflow\EditorTemplates\ComboBox.cshtml"
                                     Write(op.Caption);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 9 "..\..\Areas\Sph\Views\Workflow\EditorTemplates\ComboBox.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </select>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
