#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Areas.App.Views.Shared.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/App/Views/Shared/EditorTemplates/TextBox.cshtml")]
    public partial class TextBox : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.TextBox>
    {
        public TextBox()
        {
        }
        public override void Execute()
        {

WriteLiteral(@"
<!--ko if: ko.unwrap($type) === ""Bespoke.Sph.Domain.TextBox, domain.sph"" -->
<div class=""form-group"">
    <label for=""fetb-entity"">Autocompletion Entity</label>
    <select id=""fetb-entity"" class=""form-control"" data-bind=""value: AutoCompletionEntity,
                options : $root.entityOptions,
                optionsValue : 'value',
                optionsText : 'text',
                optionsCaption: '[Select Entity]'"" name=""entity""></select>
</div>
<div class=""form-group"">
    <label for=""fetb-field"">Autocompletion Field</label>
    <input class=""form-control"" data-bind=""value: AutoCompletionField,entityTypeaheadPath : AutoCompletionEntity,enable:AutoCompletionEntity()"" id=""fetb-field"" type=""text"" name=""Field"" />
</div>
<div class=""form-group"">
    <label for=""fetb-Query"">Autocompletion Query</label>
    <input class=""form-control"" data-bind=""value: AutoCompletionQuery,enable:AutoCompletionEntity()"" id=""fetb-Query"" type=""text"" name=""Query"" />
</div>

<!--/ko-->
");


        }
    }
}
#pragma warning restore 1591
