#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    
    #line 2 "..\..\Areas\Sph\Views\Shared\_PublicLayout.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sph/Views/Shared/_PublicLayout.cshtml")]
    public partial class _Areas_Sph_Views_Shared__PublicLayout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Sph_Views_Shared__PublicLayout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n");

WriteLiteral("<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 104), Tuple.Create("\"", 124)
, Tuple.Create(Tuple.Create("", 111), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 111), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 8 "..\..\Areas\Sph\Views\Shared\_PublicLayout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 290), Tuple.Create("\"", 318)
, Tuple.Create(Tuple.Create("", 297), Tuple.Create<System.Object, System.Int32>(Href("~/Content/_public.css")
, 297), false)
);

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" media=\"screen\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Areas\Sph\Views\Shared\_PublicLayout.cshtml"
Write(Scripts.Render("~/scripts/public"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Areas\Sph\Views\Shared\_PublicLayout.cshtml"
Write(RenderSection("head_script", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n\r\n<body>\r\n    <header>\r\n        <div");

WriteLiteral(" class=\"menu-row\"");

WriteLiteral(">\r\n            <nav");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"menu\"");

WriteLiteral(">\r\n                        <li>");

            
            #line 19 "..\..\Areas\Sph\Views\Shared\_PublicLayout.cshtml"
                       Write(Html.ActionLink("Home","Index","Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        <li>");

            
            #line 20 "..\..\Areas\Sph\Views\Shared\_PublicLayout.cshtml"
                       Write(Html.ActionLink("Features","Features","Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        <li><a");

WriteLiteral(" href=\"http://demo.sph.my\"");

WriteLiteral(">Demo</a></li>\r\n                        <li>");

            
            #line 22 "..\..\Areas\Sph\Views\Shared\_PublicLayout.cshtml"
                       Write(Html.ActionLink("Contact Us","ContactUs","Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                    </ul>\r\n                </nav>\r\n        </div>\r\n       " +
" <div>\r\n            <span>Sistem Pengurusan Harta</span>\r\n        </div>\r\n    </" +
"header>\r\n    <section");

WriteLiteral(" id=\"content\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 31 "..\..\Areas\Sph\Views\Shared\_PublicLayout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </section>\r\n    <footer>\r\n\t\t<p>Copyright 2013 BeSpoke Technology Sdn Bhd</p" +
">\r\n\t</footer>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
