#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Areas.Sph.Views.Shared.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sph/Views/Shared/EditorTemplates/FileUploadElement.cshtml")]
    public partial class _FileUploadElement : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.FileUploadElement>
    {
        public _FileUploadElement()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
  
    var required = Model.IsRequired ? "required" : null;
    if (string.IsNullOrWhiteSpace(Model.Enable))
    {
        Model.Enable = "true";
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 9 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
 if (Model.IsCompact)
{

            
            #line default
            #line hidden
WriteLiteral("    <input ");

            
            #line 11 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
      Write(required);

            
            #line default
            #line hidden
WriteLiteral(" class=\"");

            
            #line 11 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
                        Write(Model.CssClass + " form-control " + Model.Size);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");

            
            #line 11 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
                                                                                 Write(Model.Tooltip);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n           data-bind=\"");

            
            #line 12 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
                  Write(Html.Raw(Model.GetKnockoutBindingExpression()));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n           id=\"");

            
            #line 13 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
          Write(Model.ElementId);

            
            #line default
            #line hidden
WriteLiteral("\" type=\"file\" name=\"files\" />\r\n");

            
            #line 14 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
}
else
{


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" data-bind=\"visible:");

            
            #line 18 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
                       Write(Model.Visible);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <label");

WriteAttribute("for", Tuple.Create(" for=\"", 564), Tuple.Create("\"", 586)
            
            #line 19 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
, Tuple.Create(Tuple.Create("", 570), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 570), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 587), Tuple.Create("\"", 615)
            
            #line 19 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
, Tuple.Create(Tuple.Create("", 595), Tuple.Create<System.Object, System.Int32>(Model.LabelCssClass
            
            #line default
            #line hidden
, 595), false)
);

WriteLiteral(">");

            
            #line 19 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
                                                              Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 651), Tuple.Create("\"", 684)
            
            #line 20 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
, Tuple.Create(Tuple.Create("", 659), Tuple.Create<System.Object, System.Int32>(Model.InputPanelCssClass
            
            #line default
            #line hidden
, 659), false)
);

WriteLiteral(">\r\n            <input ");

            
            #line 21 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
              Write(required);

            
            #line default
            #line hidden
WriteLiteral(" class=\"");

            
            #line 21 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
                                Write(Model.CssClass + " form-control " + Model.Size);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");

            
            #line 21 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
                                                                                         Write(Model.Tooltip);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                   data-bind=\"");

            
            #line 22 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
                          Write(Html.Raw(Model.GetKnockoutBindingExpression()));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                   id=\"");

            
            #line 23 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
                  Write(Model.ElementId);

            
            #line default
            #line hidden
WriteLiteral("\" type=\"file\" name=\"files\" />\r\n        </div>\r\n");

            
            #line 25 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
        
            
            #line default
            #line hidden
            
            #line 25 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
         if (!string.IsNullOrWhiteSpace(Model.HelpText))
        {

            
            #line default
            #line hidden
WriteLiteral("            <span");

WriteLiteral(" class=\"help-block\"");

WriteLiteral(">");

            
            #line 27 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
                                Write(Model.HelpText);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 28 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 30 "..\..\Areas\Sph\Views\Shared\EditorTemplates\FileUploadElement.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
