#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sph/Views/Home/_messagesHeader.cshtml")]
    public partial class _Areas_Sph_Views_Home__messagesHeader_cshtml : System.Web.Mvc.WebViewPage<Bespoke.Sph.Web.ViewModels.SphIndexViewModel>
    {
        public _Areas_Sph_Views_Home__messagesHeader_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!-- BEGIN INBOX DROPDOWN -->\r\n<!-- DOC: Apply \"dropdown-dark\" class after below " +
"\"dropdown-extended\" to change the dropdown styte -->\r\n<li");

WriteLiteral(" class=\"dropdown dropdown-extended dropdown-inbox\"");

WriteLiteral(" id=\"header_inbox_bar\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" data-hover=\"dropdown\"");

WriteLiteral(" data-close-others=\"true\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"icon-envelope-open\"");

WriteLiteral("></i>\r\n        <span");

WriteLiteral(" class=\"badge badge-default\"");

WriteLiteral(" data-bind=\"text:unread\"");

WriteLiteral(">\r\n        </span>\r\n    </a>\r\n    <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(" style=\"left: -124px\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"external\"");

WriteLiteral(">\r\n            <h3>\r\n                You have <span");

WriteLiteral(" class=\"bold\"");

WriteLiteral(">\r\n                    <!-- ko text: unread -->\r\n                    <!-- /ko-->\r" +
"\n                </span> new messages\r\n            </h3>\r\n            <a");

WriteLiteral(" href=\"#message.inbox\"");

WriteLiteral(">View all</a>\r\n        </li>\r\n        <li>\r\n            <ul");

WriteLiteral(" class=\"dropdown-menu-list scroller\"");

WriteLiteral(" style=\"height: 275px;\"");

WriteLiteral(" data-handle-color=\"#637283\"");

WriteLiteral(" data-bind=\"foreach:messages\"");

WriteLiteral(">\r\n\r\n                <li>\r\n                    <a");

WriteLiteral(" data-bind=\"attr : {\'href\' : \'#message.detail/\' + ko.unwrap(Id)}\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"photo\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-user fa2x\"");

WriteLiteral("></i>\r\n                        </span>\r\n                        <span");

WriteLiteral(" class=\"subject\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"from\"");

WriteLiteral("></span>\r\n                            <span");

WriteLiteral(" class=\"time\"");

WriteLiteral(" data-bind=\"text: $parent.getTimeSpan($data)\"");

WriteLiteral("> </span>\r\n                        </span>\r\n                        <span");

WriteLiteral(" class=\"message\"");

WriteLiteral(" data-bind=\"text: Subject\"");

WriteLiteral("></span>\r\n                    </a>\r\n                </li>\r\n\r\n\r\n            </ul>\r" +
"\n        </li>\r\n    </ul>\r\n</li>\r\n");

        }
    }
}
#pragma warning restore 1591
