#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Areas.Sph.Views.Home
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Areas\Sph\Views\Home\index.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\Areas\Sph\Views\Home\index.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Sph\Views\Home\index.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sph/Views/Home/index.cshtml")]
    public partial class index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public index()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Sph\Views\Home\index.cshtml"
  
    Layout = null;
    var theme = ConfigurationManager.AppSettings["theme"];

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>");

            
            #line 11 "..\..\Areas\Sph\Views\Home\index.cshtml"
      Write(Bespoke.Sph.Domain.ConfigurationManager.ApplicationName);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge, chrome=1\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"apple-mobile-web-app-capable\"");

WriteLiteral(" content=\"yes\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"apple-mobile-web-app-status-bar-style\"");

WriteLiteral(" content=\"black\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"format-detection\"");

WriteLiteral(" content=\"telephone=no\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(" />\r\n\r\n    ");

WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 717), Tuple.Create("\"", 741)
, Tuple.Create(Tuple.Create("", 724), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css.css")
, 724), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 773), Tuple.Create("\"", 803)
, Tuple.Create(Tuple.Create("", 780), Tuple.Create<System.Object, System.Int32>(Href("~/Content/nprogress.css")
, 780), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 835), Tuple.Create("\"", 875)
, Tuple.Create(Tuple.Create("", 842), Tuple.Create<System.Object, System.Int32>(Href("~/Content/daterangepicker-bs3.css")
, 842), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"The description of my page\"");

WriteLiteral(" />\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" id=\"applicationHost\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 27 "..\..\Areas\Sph\Views\Home\index.cshtml"
   Write(Html.Partial("_splash"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    ");

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1371), Tuple.Create("\"", 1403)
, Tuple.Create(Tuple.Create("", 1377), Tuple.Create<System.Object, System.Int32>(Href("~/SphApp/objectbuilders.js")
, 1377), false)
);

WriteLiteral("></script>\r\n");

            
            #line 37 "..\..\Areas\Sph\Views\Home\index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 37 "..\..\Areas\Sph\Views\Home\index.cshtml"
     if (HttpContext.Current.IsDebuggingEnabled)
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1488), Tuple.Create("\"", 1513)
, Tuple.Create(Tuple.Create("", 1494), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/vendor.js")
, 1494), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1541), Tuple.Create("\"", 1569)
, Tuple.Create(Tuple.Create("", 1547), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/nprogress.js")
, 1547), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1597), Tuple.Create("\"", 1626)
, Tuple.Create(Tuple.Create("", 1603), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jstree.min.js")
, 1603), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1654), Tuple.Create("\"", 1677)
, Tuple.Create(Tuple.Create("", 1660), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/core.js")
, 1660), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1705), Tuple.Create("\"", 1734)
, Tuple.Create(Tuple.Create("", 1711), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/_ko.entity.js")
, 1711), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1762), Tuple.Create("\"", 1794)
, Tuple.Create(Tuple.Create("", 1768), Tuple.Create<System.Object, System.Int32>(Href("~/SphApp/schemas/domain.js")
, 1768), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1822), Tuple.Create("\"", 1861)
, Tuple.Create(Tuple.Create("", 1828), Tuple.Create<System.Object, System.Int32>(Href("~/SphApp/prototypes/prototypes.js")
, 1828), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1889), Tuple.Create("\"", 1922)
, Tuple.Create(Tuple.Create("", 1895), Tuple.Create<System.Object, System.Int32>(Href("~/SphApp/partial/partial.js")
, 1895), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1973), Tuple.Create("\"", 2005)
, Tuple.Create(Tuple.Create("", 1979), Tuple.Create<System.Object, System.Int32>(Href("~/entitydefinition/schemas")
, 1979), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2033), Tuple.Create("\"", 2070)
, Tuple.Create(Tuple.Create("", 2039), Tuple.Create<System.Object, System.Int32>(Href("~/Content/theme.")
, 2039), false)
            
            #line 48 "..\..\Areas\Sph\Views\Home\index.cshtml"
, Tuple.Create(Tuple.Create("", 2055), Tuple.Create<System.Object, System.Int32>(theme
            
            #line default
            #line hidden
, 2055), false)
, Tuple.Create(Tuple.Create("", 2061), Tuple.Create("/theme.js", 2061), true)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2098), Tuple.Create("\"", 2127)
, Tuple.Create(Tuple.Create("", 2104), Tuple.Create<System.Object, System.Int32>(Href("~/kendo/js/kendo.all.js")
, 2104), false)
);

WriteLiteral("></script>\r\n");

            
            #line 50 "..\..\Areas\Sph\Views\Home\index.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2179), Tuple.Create("\"", 2208)
, Tuple.Create(Tuple.Create("", 2185), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/vendor.min.js")
, 2185), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2236), Tuple.Create("\"", 2265)
, Tuple.Create(Tuple.Create("", 2242), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jstree.min.js")
, 2242), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2293), Tuple.Create("\"", 2320)
, Tuple.Create(Tuple.Create("", 2299), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/core.min.js")
, 2299), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2348), Tuple.Create("\"", 2376)
, Tuple.Create(Tuple.Create("", 2354), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/nprogress.js")
, 2354), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2404), Tuple.Create("\"", 2437)
, Tuple.Create(Tuple.Create("", 2410), Tuple.Create<System.Object, System.Int32>(Href("~/Sph/schemas/domain.min.js")
, 2410), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2465), Tuple.Create("\"", 2505)
, Tuple.Create(Tuple.Create("", 2471), Tuple.Create<System.Object, System.Int32>(Href("~/Sph/prototypes/prototypes.min.js")
, 2471), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2533), Tuple.Create("\"", 2567)
, Tuple.Create(Tuple.Create("", 2539), Tuple.Create<System.Object, System.Int32>(Href("~/Sph/partial/partial.min.js")
, 2539), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2618), Tuple.Create("\"", 2650)
, Tuple.Create(Tuple.Create("", 2624), Tuple.Create<System.Object, System.Int32>(Href("~/entitydefinition/schemas")
, 2624), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2678), Tuple.Create("\"", 2715)
, Tuple.Create(Tuple.Create("", 2684), Tuple.Create<System.Object, System.Int32>(Href("~/Content/theme.")
, 2684), false)
            
            #line 61 "..\..\Areas\Sph\Views\Home\index.cshtml"
, Tuple.Create(Tuple.Create("", 2700), Tuple.Create<System.Object, System.Int32>(theme
            
            #line default
            #line hidden
, 2700), false)
, Tuple.Create(Tuple.Create("", 2706), Tuple.Create("/theme.js", 2706), true)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2743), Tuple.Create("\"", 2772)
, Tuple.Create(Tuple.Create("", 2749), Tuple.Create<System.Object, System.Int32>(Href("~/kendo/js/kendo.all.js")
, 2749), false)
);

WriteLiteral("></script>\r\n");

            
            #line 63 "..\..\Areas\Sph\Views\Home\index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2830), Tuple.Create("\"", 2856)
, Tuple.Create(Tuple.Create("", 2836), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/require.js")
, 2836), false)
);

WriteLiteral(" data-main=\"SphApp/main\"");

WriteLiteral("></script>\r\n\r\n\r\n\r\n    ");

WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
