[
  {
    "role": null,
    "groupName": "Main",
    "route": "public.index",
    "moduleId": "viewmodels/public.index",
    "title": "Utama",
    "nav": true,
    "icon": "fa-home",
    "caption": "Utama",
    "settings": null,
    "isAdminPage": false,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_user",
    "groupName": "Users",
    "route": "users",
    "moduleId": "viewmodels/users",
    "title": "Users management",
    "nav": false,
    "icon": "fa-user",
    "caption": "Users",
    "settings": null,
    "isAdminPage": true,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_setting",
    "groupName": "Settings",
    "route": "organization.detail",
    "moduleId": "viewmodels/organization.detail",
    "title": "Tetapan Organisasi",
    "nav": false,
    "icon": "fa-group",
    "caption": "org",
    "settings": null,
    "isAdminPage": true,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "everybody",
    "groupName": null,
    "route": "user.profile",
    "moduleId": "viewmodels/user.profile",
    "title": "Profile",
    "nav": false,
    "icon": null,
    "caption": null,
    "settings": null,
    "isAdminPage": false,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_user",
    "groupName": "Settings",
    "route": "role.settings/:id",
    "moduleId": "viewmodels/role.settings",
    "title": null,
    "nav": false,
    "icon": null,
    "caption": null,
    "settings": null,
    "isAdminPage": false,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_setting",
    "groupName": "Settings",
    "route": "setting",
    "moduleId": "viewmodels/setting",
    "title": "Tetapan Umum",
    "nav": false,
    "icon": "fa-gear",
    "caption": "Setting",
    "settings": {
      "caption": "Settings"
    },
    "isAdminPage": true,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_add_trigger",
    "groupName": null,
    "route": "trigger.setup/:id",
    "moduleId": "viewmodels/trigger.setup",
    "title": "Setting Trigger",
    "nav": false,
    "icon": "fa-flag",
    "caption": "Setting Trigger",
    "settings": null,
    "isAdminPage": false,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_add_trigger",
    "groupName": "Workflow",
    "route": "trigger.list",
    "moduleId": "viewmodels/trigger.list",
    "title": "Senarai Trigger",
    "nav": false,
    "icon": "fa-flag",
    "caption": "Senarai Trigger",
    "settings": null,
    "isAdminPage": true,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "everybody",
    "groupName": null,
    "route": "message.detail/:id",
    "moduleId": "viewmodels/message.detail",
    "title": "Mesej",
    "nav": false,
    "icon": "fa-check",
    "caption": "Mesej",
    "settings": null,
    "isAdminPage": false,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "everybody",
    "groupName": null,
    "route": "message.inbox",
    "moduleId": "viewmodels/message.inbox",
    "title": "Mesej",
    "nav": false,
    "icon": "fa-envelope",
    "caption": "Mesej",
    "settings": null,
    "isAdminPage": false,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_dashboard",
    "groupName": null,
    "route": "reportdefinition.edit/:id",
    "moduleId": "viewmodels/reportdefinition.edit",
    "title": "Report Builder",
    "nav": false,
    "icon": "fa-laptop",
    "caption": "Janaan Laporan",
    "settings": null,
    "isAdminPage": false,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_dashboard",
    "groupName": "Report Builder",
    "route": "reportdefinition.list",
    "moduleId": "viewmodels/reportdefinition.list",
    "title": "Report Manager",
    "nav": false,
    "icon": "fa-dribbble",
    "caption": "Report Manager",
    "settings": null,
    "isAdminPage": true,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_dashboard",
    "groupName": null,
    "route": "reportdelivery.schedule/:rdlid",
    "moduleId": "viewmodels/reportdelivery.schedule",
    "title": "Report Schedules",
    "nav": false,
    "icon": "fa-calendar",
    "caption": "Report Schedules",
    "settings": null,
    "isAdminPage": false,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_workflow",
    "groupName": "Workflow",
    "route": "workflow.definition.list",
    "moduleId": "viewmodels/workflow.definition.list",
    "title": "Workflow Definition list",
    "nav": false,
    "icon": "fa-gears",
    "caption": "Workflows Home",
    "settings": null,
    "isAdminPage": true,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_workflow",
    "groupName": "Admin",
    "route": "admin.home",
    "moduleId": "viewmodels/admin.home",
    "title": "Administrator landing page",
    "nav": true,
    "icon": "fa-gears",
    "caption": "Administrator Home",
    "settings": null,
    "isAdminPage": false,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_workflow",
    "groupName": "Workflow",
    "route": "workflow.instances.console",
    "moduleId": "viewmodels/workflow.instances.console",
    "title": "Management consoles",
    "nav": false,
    "icon": "fa-briefcase",
    "caption": "Workflow management consoles",
    "settings": null,
    "isAdminPage": true,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_workflow",
    "groupName": "Workflow",
    "route": "entities.list",
    "moduleId": "viewmodels/entities.list",
    "title": "Custom Entities Consoles",
    "nav": false,
    "icon": "fa-briefcase",
    "caption": "Custom Entitites consoles",
    "settings": null,
    "isAdminPage": true,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_workflow",
    "groupName": "Workflow",
    "route": "workflow.activities/:id",
    "moduleId": "viewmodels/workflow.activities",
    "title": "Instant Activity logs",
    "nav": false,
    "icon": "fa-bug",
    "caption": "Workflow Instant Activities",
    "settings": null,
    "isAdminPage": false,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_workflow",
    "groupName": "Entity",
    "route": "entity.details/:id",
    "moduleId": "viewmodels/entity.details",
    "title": "Custom Entity",
    "nav": false,
    "icon": "fa-bug",
    "caption": "Custom Entity",
    "settings": null,
    "isAdminPage": false,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_workflow",
    "groupName": "Entity",
    "route": "entity.form.designer/:entityid/:formid",
    "moduleId": "viewmodels/entity.form.designer",
    "title": "Entity Form Designer",
    "nav": false,
    "icon": "fa-bug",
    "caption": "Entity Form Designer",
    "settings": null,
    "isAdminPage": false,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_workflow",
    "groupName": "Workflow",
    "route": "workflow.debugger/:id",
    "moduleId": "viewmodels/workflow.debugger",
    "title": "Instant Debugger",
    "nav": false,
    "icon": "fa-bug",
    "caption": "Workflow Instant debugger",
    "settings": null,
    "isAdminPage": false,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_workflow",
    "groupName": "Workflow",
    "route": "workflow.definition.visual/:id",
    "moduleId": "viewmodels/workflow.definition.visual",
    "title": "Workflow Visual Designer",
    "nav": false,
    "icon": null,
    "caption": "Workflow visual",
    "settings": null,
    "isAdminPage": false,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_workflow",
    "groupName": "Workflow",
    "route": "page.list",
    "moduleId": "viewmodels/page.list",
    "title": "Page list",
    "nav": true,
    "icon": "fa-list-alt",
    "caption": "Pages",
    "settings": null,
    "isAdminPage": true,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_investigate",
    "groupName": "Workflow",
    "route": "workflow.draft",
    "moduleId": "viewmodels/workflow.draft",
    "title": "Draft Workflow",
    "nav": false,
    "icon": "fa-edit",
    "caption": "Workflow Draft",
    "settings": null,
    "isAdminPage": true,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_workflow",
    "groupName": "Workflow",
    "route": "workflow.manage/:id",
    "moduleId": "viewmodels/workflow.manage",
    "title": "Manage worflows",
    "nav": false,
    "icon": "fa-gear:before,\r\n.fa-cog",
    "caption": "Manage Workflow",
    "settings": null,
    "isAdminPage": false,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_workflow",
    "groupName": "Workflow",
    "route": "screen.editor/:wdid/:webid",
    "moduleId": "viewmodels/screen.editor",
    "title": "Screen Designer",
    "nav": false,
    "icon": "fa-pagelines",
    "caption": "Screen Editor",
    "settings": null,
    "isAdminPage": false,
    "showWhenLoggedIn": false,
    "error": ""
  }
]