[
  {
      "role": null,
      "groupName": "Main",
      "route": "public.index",
      "moduleId": "viewmodels/public.index",
      "title": "Home",
      "nav": true,
      "icon": "fa fa-home",
      "caption": "Home",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": null,
      "groupName": "Main",
      "route": "not.found",
      "moduleId": "viewmodels/not.found",
      "title": "Home",
      "nav": false,
      "icon": "fa fa-home",
      "caption": "Not Found",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": true,
      "error": ""
  },
  {
      "role": "administrators",
      "groupName": "Security",
      "route": "users",
      "moduleId": "viewmodels/users",
      "title": "Users management",
      "nav": false,
      "icon": "fa fa-user",
      "caption": "Users",
      "settings": null,
      "isAdminPage": true,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "administrators",
      "groupName": "Settings",
      "route": "organization.detail",
      "moduleId": "viewmodels/organization.detail",
      "title": "Organisation settings",
      "nav": false,
      "icon": "fa fa-group",
      "caption": "org",
      "settings": null,
      "isAdminPage": true,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "everybody",
      "groupName": null,
      "route": "user.profile",
      "moduleId": "viewmodels/user.profile",
      "title": "Profile",
      "nav": false,
      "icon": null,
      "caption": null,
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "administrators",
      "groupName": "Settings",
      "route": "role.settings/:id",
      "moduleId": "viewmodels/role.settings",
      "title": null,
      "nav": false,
      "icon": null,
      "caption": null,
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "administrators",
      "groupName": "Settings",
      "route": "setting",
      "moduleId": "viewmodels/setting",
      "title": "General settings",
      "nav": false,
      "icon": "fa fa-gear",
      "caption": "Setting",
      "settings": {
          "caption": "Settings"
      },
      "isAdminPage": true,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": null,
      "route": "entity.operation.details/:id/:name",
      "moduleId": "viewmodels/entity.operation.details",
      "title": "Operation",
      "nav": false,
      "icon": "fa fa-gavel",
      "caption": "Operation",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": null,
      "route": "email.template.details/:id",
      "moduleId": "viewmodels/email.template.details",
      "title": "Email Template",
      "nav": false,
      "icon": "fa fa-envelope",
      "caption": "Email Template",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": null,
      "route": "document.template.details/:id",
      "moduleId": "viewmodels/document.template.details",
      "title": "Document Template",
      "nav": false,
      "icon": "fa fa-envelope",
      "caption": "Document Template",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": null,
      "route": "trigger.setup/:id",
      "moduleId": "viewmodels/trigger.setup",
      "title": "Setting Trigger",
      "nav": false,
      "icon": "fa fa-bolt",
      "caption": "Setting Trigger",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Workflow",
      "route": "trigger.list",
      "moduleId": "viewmodels/trigger.list",
      "title": "Triggers",
      "nav": false,
      "icon": "fa fa-bolt",
      "caption": "Triggers",
      "settings": null,
      "isAdminPage": true,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "everybody",
      "groupName": null,
      "route": "message.detail/:id",
      "moduleId": "viewmodels/message.detail",
      "title": "Message",
      "nav": false,
      "icon": "fa fa-check",
      "caption": "Message",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "everybody",
      "groupName": null,
      "route": "message.inbox",
      "moduleId": "viewmodels/message.inbox",
      "title": "Message",
      "nav": false,
      "icon": "fa fa-envelope",
      "caption": "Message",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": null,
      "route": "reportdefinition.edit/:id",
      "moduleId": "viewmodels/reportdefinition.edit",
      "title": "Report Builder",
      "nav": false,
      "icon": "fa fa-laptop",
      "caption": "Janaan Laporan",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Report Builder",
      "route": "reportdefinition.list",
      "moduleId": "viewmodels/reportdefinition.list",
      "title": "Report Manager",
      "nav": false,
      "icon": "fa fa-bar-chart-o",
      "caption": "Report Manager",
      "settings": null,
      "isAdminPage": true,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": null,
      "route": "reportdelivery.schedule/:rdlid",
      "moduleId": "viewmodels/reportdelivery.schedule",
      "title": "Report Schedules",
      "nav": false,
      "icon": "fa fa-calendar",
      "caption": "Report Schedules",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Workflow",
      "route": "workflow.definition.list",
      "moduleId": "viewmodels/workflow.definition.list",
      "title": "Workflow Definition list",
      "nav": false,
      "icon": "fa fa-code-fork",
      "caption": "Workflows Home",
      "settings": null,
      "isAdminPage": true,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Dev",
      "route": "dev.home",
      "moduleId": "viewmodels/dev.home",
      "title": "Develop",
      "nav": true,
      "icon": "fa fa-code",
      "caption": "Developers Home",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "administrators",
      "groupName": "Admin",
      "route": "management.console",
      "moduleId": "viewmodels/management.console",
      "title": "Manage",
      "nav": true,
      "icon": "fa fa-gears",
      "caption": "Administrator Home",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Workflow",
      "route": "workflow.instances.console",
      "moduleId": "viewmodels/workflow.instances.console",
      "title": "Management consoles",
      "nav": false,
      "icon": "fa fa-briefcase",
      "caption": "Workflow management consoles",
      "settings": null,
      "isAdminPage": true,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Workflow",
      "route": "entities.list",
      "moduleId": "viewmodels/entities.list",
      "title": "Custom Entities Consoles",
      "nav": false,
      "icon": "fa fa-clipboard",
      "caption": "Custom Entitites consoles",
      "settings": null,
      "isAdminPage": true,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Workflow",
      "route": "workflow.activities/:id",
      "moduleId": "viewmodels/workflow.activities",
      "title": "Instant Activity logs",
      "nav": false,
      "icon": "fa fa-bug",
      "caption": "Workflow Instant Activities",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Workflow",
      "route": "workflow.kpi/:id",
      "moduleId": "viewmodels/workflow.kpi",
      "title": "Perfomance Indicator",
      "nav": false,
      "icon": "fa fa-bug",
      "caption": "Performance Indicator",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Workflow",
      "route": "workflow.overview/:id",
      "moduleId": "viewmodels/workflow.overview",
      "title": "Workflow Overview",
      "nav": false,
      "icon": "fa fa-bug",
      "caption": "Workflow Overview",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Entity",
      "route": "entity.details/:id",
      "moduleId": "viewmodels/entity.details",
      "title": "Custom Entity",
      "nav": false,
      "icon": "fa fa-bug",
      "caption": "Custom Entity",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Entity",
      "route": "entity.form.designer/:entityid/:formid",
      "moduleId": "viewmodels/entity.form.designer",
      "title": "Entity Form Designer",
      "nav": false,
      "icon": "fa fa-bug",
      "caption": "Entity Form Designer",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Entity",
      "route": "entity.view.designer/:entityid/:viewid",
      "moduleId": "viewmodels/entity.view.designer",
      "title": "Entity View Designer",
      "nav": false,
      "icon": "fa fa-bug",
      "caption": "Entity View Designer",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Entity",
      "route": "entity.business.rule.designer/:entityid/:brid",
      "moduleId": "viewmodels/entity.business.rule.designer",
      "title": "Entity Business Rule Designer",
      "nav": false,
      "icon": "fa fa-bug",
      "caption": "Entity Business Rule Designer",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Workflow",
      "route": "workflow.debugger/:id",
      "moduleId": "viewmodels/workflow.debugger",
      "title": "Instant Debugger",
      "nav": false,
      "icon": "fa fa-bug",
      "caption": "Workflow Instant debugger",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Workflow",
      "route": "workflow.definition.visual/:id",
      "moduleId": "viewmodels/workflow.definition.visual",
      "title": "Workflow Visual Designer",
      "nav": false,
      "icon": null,
      "caption": "Workflow visual",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Workflow",
      "route": "page.list/:id",
      "moduleId": "viewmodels/page.list",
      "title": "Page list",
      "nav": false,
      "icon": "fa fa-code",
      "caption": "Pages",
      "settings": null,
      "isAdminPage": true,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Workflow",
      "route": "workflow.draft",
      "moduleId": "viewmodels/workflow.draft",
      "title": "Draft Workflow",
      "nav": false,
      "icon": "fa fa-edit",
      "caption": "Workflow Draft",
      "settings": null,
      "isAdminPage": true,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Workflow",
      "route": "workflow.manage/:id",
      "moduleId": "viewmodels/workflow.manage",
      "title": "Manage worflows",
      "nav": false,
      "icon": "fa fa-gear:before,\r\n.fa-cog",
      "caption": "Manage Workflow",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  },
  {
      "role": "developers",
      "groupName": "Workflow",
      "route": "screen.editor/:wdid/:webid",
      "moduleId": "viewmodels/screen.editor",
      "title": "Screen Designer",
      "nav": false,
      "icon": "fa fa-pagelines",
      "caption": "Screen Editor",
      "settings": null,
      "isAdminPage": false,
      "showWhenLoggedIn": false,
      "error": ""
  }
]