[
  {
    "role": "can_edit_maintenance_template",
    "groupName": null,
    "url": "template.maintenance-id.0/:id",
    "moduleId": "viewmodels/template.maintenance-id.0",
    "name": "Tetapan Penyenggaraan",
    "visible": false,
    "icon": null,
    "caption": null,
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_maintenance_template",
    "groupName": null,
    "url": "maintenance.template.list",
    "moduleId": "viewmodels/maintenance.template.list",
    "name": "Templat Penyelenggaraan",
    "visible": true,
    "icon": "icon-flag",
    "caption": "Senarai Templat Penyelenggaraan",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "maintenance_dashboard",
    "groupName": null,
    "url": "maintenance.dashboard",
    "moduleId": "viewmodels/maintenance.dashboard",
    "name": "Papan Senggara",
    "visible": true,
    "icon": "icon-gear",
    "caption": "Papan Senggara",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_assign_complaint",
    "groupName": null,
    "url": "complaint.dashboard",
    "moduleId": "viewmodels/complaint.dashboard",
    "name": "Papan Aduan",
    "visible": true,
    "icon": "icon-flag",
    "caption": "Papan Aduan",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": null,
    "groupName": "Main",
    "url": "public.index",
    "moduleId": "viewmodels/public.index",
    "name": "Utama",
    "visible": true,
    "icon": "icon-home",
    "caption": "Utama",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_dashboard",
    "groupName": null,
    "url": "admindashboard",
    "moduleId": "viewmodels/admindashboard",
    "name": "Papan Tugas",
    "visible": true,
    "icon": "icon-home",
    "caption": "Papan Tugas",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "maintenance_dashboard",
    "groupName": null,
    "url": "maintenance.detail/:templateId/:id",
    "moduleId": "viewmodels/maintenance.detail",
    "name": "Perincian Senggara",
    "visible": false,
    "icon": null,
    "caption": null,
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_contract_template",
    "groupName": null,
    "url": "contract.template/:id",
    "moduleId": "viewmodels/contract.template",
    "name": "contract type",
    "visible": false,
    "icon": "icon-edit",
    "caption": "Buat jenis kontrak",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_dashboard",
    "groupName": null,
    "url": "offerdetails/:rentalId/:csId",
    "moduleId": "viewmodels/offerdetails",
    "name": "Tawaran",
    "visible": false,
    "icon": "icon-envelope-alt",
    "caption": "Tawaran",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_add_space",
    "groupName": null,
    "url": "lot.list/:buildingId/:block/:floorname",
    "moduleId": "viewmodels/lotdetail",
    "name": "Senarai lots",
    "visible": false,
    "icon": "icon-tablet",
    "caption": "Lot Details",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_setting",
    "groupName": null,
    "url": "contract.list",
    "moduleId": "viewmodels/contract.list",
    "name": "Kontrak",
    "visible": true,
    "icon": "icon-briefcase",
    "caption": "Kontraks",
    "settings": {
      "caption": "Senarai Kontraks"
    },
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_view_contract_details",
    "groupName": null,
    "url": "contract.details/:id",
    "moduleId": "viewmodels/contract.details",
    "name": "contractdetails",
    "visible": false,
    "icon": "icon-book",
    "caption": "Kontraks",
    "settings": {
      "caption": "Maklumat Kontraks"
    },
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_add_building",
    "groupName": null,
    "url": "building.list",
    "moduleId": "viewmodels/building.list",
    "name": "Bangunan",
    "visible": true,
    "icon": "icon-building",
    "caption": "Building",
    "settings": {
      "caption": "Senarai Bangunan"
    },
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_add_space",
    "groupName": null,
    "url": "space.detail/:templateId/:buildingId/:floorname/:csId",
    "moduleId": "viewmodels/space.detail",
    "name": "ruang komersial",
    "visible": false,
    "icon": "icon-road",
    "caption": " space",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_user",
    "groupName": null,
    "url": "users",
    "moduleId": "viewmodels/users",
    "name": "Pengurusan Pengguna",
    "visible": true,
    "icon": "icon-user",
    "caption": "Pengguna",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_add_space",
    "groupName": null,
    "url": "space.list",
    "moduleId": "viewmodels/space.list",
    "name": "Ruang",
    "visible": true,
    "icon": "icon-columns",
    "caption": "Senarai Ruang",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_dashboard",
    "groupName": null,
    "url": "contract.create/:rentalApplicationId",
    "moduleId": "viewmodels/contract.create",
    "name": "create contract",
    "visible": false,
    "icon": "icon-edit-sign",
    "caption": "Buat kontrak",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_contract_template",
    "groupName": null,
    "url": "contract.template.list",
    "moduleId": "viewmodels/contract.template.list",
    "name": "Templat Kontrak",
    "visible": true,
    "icon": "icon-edit",
    "caption": "Buat jenis kontrak",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_add_building",
    "groupName": null,
    "url": "building.bound",
    "moduleId": "viewmodels/building.bound",
    "name": "Peta Kawasan",
    "visible": true,
    "icon": "icon-map-marker",
    "caption": "Peta Kawasan",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_add_building",
    "groupName": null,
    "url": "building.detail/:templateId/:id",
    "moduleId": "viewmodels/building.detail",
    "name": "BuildingDetail",
    "visible": false,
    "icon": "icon-building",
    "caption": "Building Details",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_add_space",
    "groupName": null,
    "url": "floorplan/:buildingId/:floorname",
    "moduleId": "viewmodels/floorplan",
    "name": "FloorPlan",
    "visible": false,
    "icon": "icon-picture",
    "caption": "Floor plan",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_dashboard",
    "groupName": null,
    "url": "applicationlist/:status",
    "moduleId": "viewmodels/applicationlist",
    "name": "applicationlist",
    "visible": false,
    "icon": "icon-list",
    "caption": "Senarai Permohonan",
    "settings": {
      "caption": "Senarai permohonan"
    },
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_dashboard",
    "groupName": null,
    "url": "rentalapplication.verify/:applicationId",
    "moduleId": "viewmodels/rentalapplication.verify",
    "name": "rentalapplication.verify",
    "visible": false,
    "icon": "icon-inbox",
    "caption": "Senarai Permohonan",
    "settings": {
      "caption": "Maklumat permohonan"
    },
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_dashboard",
    "groupName": null,
    "url": "returnedapplication/:id",
    "moduleId": "viewmodels/returnedapplication",
    "name": "rental application",
    "visible": false,
    "icon": "icon-mail-reply",
    "caption": "returnedapplication",
    "settings": {
      "caption": "Kembalikan Permohonan"
    },
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_dashboard",
    "groupName": null,
    "url": "tenant",
    "moduleId": "viewmodels/tenant",
    "name": "Penyewa",
    "visible": true,
    "icon": "icon-user",
    "caption": "Penyewa",
    "settings": {
      "caption": "Senarai tenant"
    },
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_payment",
    "groupName": null,
    "url": "deposit",
    "moduleId": "viewmodels/deposit",
    "name": "Bayaran Deposit",
    "visible": true,
    "icon": "icon-money",
    "caption": "deposit",
    "settings": {
      "caption": "Senarai deposit"
    },
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_payment",
    "groupName": null,
    "url": "rebate",
    "moduleId": "viewmodels/rebate",
    "name": "Senarai Rebat",
    "visible": true,
    "icon": "icon-usd",
    "caption": "Rebat",
    "settings": {
      "caption": "Rebat"
    },
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_dashboard",
    "groupName": null,
    "url": "tenant.detail/:tenantId",
    "moduleId": "viewmodels/tenant.detail",
    "name": "tenant.detail",
    "visible": false,
    "icon": "icon-user",
    "caption": "penyewa",
    "settings": {
      "caption": "Penyewa"
    },
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_payment",
    "groupName": null,
    "url": "payment",
    "moduleId": "viewmodels/payment",
    "name": "Bayaran Sewa",
    "visible": true,
    "icon": "icon-credit-card",
    "caption": "Bayaran",
    "settings": {
      "caption": "Bayaran"
    },
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_setting",
    "groupName": null,
    "url": "organization.detail",
    "moduleId": "viewmodels/organization.detail",
    "name": "Tetapan Organisasi",
    "visible": true,
    "icon": "icon-group",
    "caption": "org",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_complaint_template",
    "groupName": null,
    "url": "complaint.template.list",
    "moduleId": "viewmodels/complaint.template.list",
    "name": "Templat Aduan",
    "visible": true,
    "icon": "icon-comments-alt",
    "caption": "aduan",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_complaint_template",
    "groupName": null,
    "url": "template.complaint-id.0/:id",
    "moduleId": "viewmodels/template.complaint-id.0",
    "name": "Tetapan Aduan",
    "visible": false,
    "icon": "icon-comments-alt",
    "caption": "aduan",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_assign_complaint",
    "groupName": null,
    "url": "complaint.list/:status",
    "moduleId": "viewmodels/complaint.list",
    "name": "Senarai Aduan",
    "visible": false,
    "icon": "icon-tasks",
    "caption": "Senarai Aduan",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_view_tenant_details",
    "groupName": null,
    "url": "tenant.portal",
    "moduleId": "viewmodels/tenant.portal",
    "name": "Portal Penyewa",
    "visible": true,
    "icon": "icon-user",
    "caption": "Portal Penyewa",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_assign_complaint",
    "groupName": null,
    "url": "complaint.close/:id",
    "moduleId": "viewmodels/complaint.close",
    "name": "Penyenggaraan",
    "visible": false,
    "icon": "icon-wrench",
    "caption": "Penyenggaraan",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "everybody",
    "groupName": null,
    "url": "user.profile",
    "moduleId": "viewmodels/user.profile",
    "name": "Profile",
    "visible": false,
    "icon": null,
    "caption": null,
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "maintenance_dashboard",
    "groupName": null,
    "url": "maintenance.list/:status",
    "moduleId": "viewmodels/maintenance.list",
    "name": "Senarai Penyenggaraan",
    "visible": false,
    "icon": "icon-list-alt",
    "caption": "Senarai Penyenggaraan",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "maintenance_officer",
    "groupName": null,
    "url": "workorder.list",
    "moduleId": "viewmodels/workorder.list",
    "name": "Senarai Arahan Kerja",
    "visible": true,
    "icon": "icon-file-text-alt",
    "caption": "Senarai Arahan Kerja",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_inventory",
    "groupName": null,
    "url": "inventory.list",
    "moduleId": "viewmodels/inventory.list",
    "name": "Senarai Inventori",
    "visible": true,
    "icon": "icon-list-ul",
    "caption": "Senarai Inventori",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_user",
    "groupName": null,
    "url": "role.settings/:id",
    "moduleId": "viewmodels/role.settings",
    "name": null,
    "visible": false,
    "icon": null,
    "caption": null,
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": null,
    "groupName": null,
    "url": "rentalapplication/:id",
    "moduleId": "viewmodels/rentalapplication",
    "name": "rental application",
    "visible": false,
    "icon": "icon-laptop",
    "caption": "rentalapplication",
    "settings": {
      "caption": "Permohonan"
    },
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": null,
    "groupName": "Application",
    "url": "rentalapplication.selectspace",
    "moduleId": "viewmodels/rentalapplication.selectspace",
    "name": "Permohonan",
    "visible": true,
    "icon": "icon-envelope",
    "caption": "permohonan",
    "settings": {
      "caption": "Permohonan"
    },
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": null,
    "groupName": null,
    "url": "complaint.form/:templateId",
    "moduleId": "viewmodels/complaint.form",
    "name": "PerincianAduan",
    "visible": false,
    "icon": "icon-edit",
    "caption": "Perinci Aduan",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": null,
    "groupName": "Complaint",
    "url": "complaint",
    "moduleId": "viewmodels/complaint",
    "name": "Aduan",
    "visible": true,
    "icon": "icon-comments",
    "caption": "Aduan",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": null,
    "groupName": null,
    "url": "complaint.detail/:id",
    "moduleId": "viewmodels/complaint.detail",
    "name": null,
    "visible": false,
    "icon": null,
    "caption": null,
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "maintenance_dashboard",
    "groupName": null,
    "url": "maintenance.assignment/:id",
    "moduleId": "viewmodels/maintenance.assignment",
    "name": "Perincian Aduan and Assisgment",
    "visible": false,
    "icon": null,
    "caption": null,
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_setting",
    "groupName": null,
    "url": "setting",
    "moduleId": "viewmodels/setting",
    "name": "Tetapan Umum",
    "visible": true,
    "icon": "icon-gear",
    "caption": "Setting",
    "settings": {
      "caption": "Settings"
    },
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_inventory",
    "groupName": null,
    "url": "inventory.detail/:id",
    "moduleId": "viewmodels/inventory.detail",
    "name": "Maklumat Inventori",
    "visible": false,
    "icon": "icon-calendar-empty",
    "caption": "Maklumat Inventori",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_add_trigger",
    "groupName": null,
    "url": "trigger.setup/:id",
    "moduleId": "viewmodels/trigger.setup",
    "name": "Setting Trigger",
    "visible": false,
    "icon": "icon-flag",
    "caption": "Setting Trigger",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_add_trigger",
    "groupName": null,
    "url": "trigger.list",
    "moduleId": "viewmodels/trigger.list",
    "name": "Senarai Trigger",
    "visible": true,
    "icon": "icon-flag",
    "caption": "Senarai Trigger",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_building_template",
    "groupName": null,
    "url": "building.template.list",
    "moduleId": "viewmodels/building.template.list",
    "name": "Templat Bangunan",
    "visible": true,
    "icon": "icon-building",
    "caption": "Senarai Templat Bangunan",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_building_template",
    "groupName": null,
    "url": "template.building-id.0/:id",
    "moduleId": "viewmodels/template.building-id.0",
    "name": "Form Templat Bangunan",
    "visible": false,
    "icon": null,
    "caption": null,
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_space_template",
    "groupName": null,
    "url": "space.template.list",
    "moduleId": "viewmodels/space.template.list",
    "name": "Templat Ruang",
    "visible": true,
    "icon": "icon-flag",
    "caption": "Senarai Templat Ruang",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_space_template",
    "groupName": null,
    "url": "template.space-id.0/:id",
    "moduleId": "viewmodels/template.space-id.0",
    "name": "Form templat ruang komersil",
    "visible": false,
    "icon": "icon-flag",
    "caption": "Form templat ruang komersil",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_application_template",
    "groupName": null,
    "url": "application.template.list",
    "moduleId": "viewmodels/application.template.list",
    "name": "Templat Permohonan",
    "visible": true,
    "icon": "icon-flag",
    "caption": "Senarai Templat Permohonan",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_application_template",
    "groupName": null,
    "url": "template.application-id.0/:id",
    "moduleId": "viewmodels/template.application-id.0",
    "name": "Form Templat Permohonan",
    "visible": false,
    "icon": null,
    "caption": "Form Templat Permohonan",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "everybody",
    "groupName": null,
    "url": "message.detail/:id",
    "moduleId": "viewmodels/message.detail",
    "name": "Mesej",
    "visible": false,
    "icon": "icon-check",
    "caption": "Mesej",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "everybody",
    "groupName": null,
    "url": "message.inbox",
    "moduleId": "viewmodels/message.inbox",
    "name": "Mesej",
    "visible": false,
    "icon": "icon-envelope",
    "caption": "Mesej",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_land",
    "groupName": null,
    "url": "land.list",
    "moduleId": "viewmodels/land.list",
    "name": "Senarai Tanah",
    "visible": true,
    "icon": "icon-flag",
    "caption": "Senarai Tanah",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "can_edit_land",
    "groupName": null,
    "url": "land.detail/:id",
    "moduleId": "viewmodels/land.detail",
    "name": "Butiran Tanah",
    "visible": false,
    "icon": "icon-flag",
    "caption": "Butiran Tanah",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_dashboard",
    "groupName": null,
    "url": "reportdefinition.edit-id.0/:id",
    "moduleId": "viewmodels/reportdefinition.edit-id.0",
    "name": "Report Builder",
    "visible": false,
    "icon": "icon-laptop",
    "caption": "Janaan Laporan",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_dashboard",
    "groupName": null,
    "url": "reportdefinition.list",
    "moduleId": "viewmodels/reportdefinition.list",
    "name": "Report Manager",
    "visible": true,
    "icon": "icon-dribbble",
    "caption": "Report Manager",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": "admin_dashboard",
    "groupName": null,
    "url": "reportdelivery.schedule/:rdlid",
    "moduleId": "viewmodels/reportdelivery.schedule",
    "name": "Report Schedules",
    "visible": false,
    "icon": "icon-calendar",
    "caption": "Report Schedules",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  },
  {
    "role": null,
    "groupName": "Complaint",
    "url": "complaint.checkstatus",
    "moduleId": "viewmodels/complaint.checkstatus",
    "name": "Semak Aduan",
    "visible": true,
    "icon": "icon-check",
    "caption": "Semak Aduan",
    "settings": null,
    "showWhenLoggedIn": false,
    "error": ""
  }
]