#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sph/Views/EntityDefinition/_RuleFieldDropDown.cshtml")]
    public partial class _Areas_Sph_Views_EntityDefinition__RuleFieldDropDown_cshtml : System.Web.Mvc.WebViewPage<Bespoke.Sph.Web.Models.TypeModel>
    {
        public _Areas_Sph_Views_EntityDefinition__RuleFieldDropDown_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Sph\Views\EntityDefinition\_RuleFieldDropDown.cshtml"
  
    var fieldTypes = System.Configuration.ConfigurationManager.AppSettings["RuleFields"].Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" data-bind=\"with : ");

            
            #line 7 "..\..\Areas\Sph\Views\EntityDefinition\_RuleFieldDropDown.cshtml"
                    Write(Model.Path);

            
            #line default
            #line hidden
WriteLiteral(", bootstrapDropDown : {}\"");

WriteLiteral(" class=\"btn btn-link dropdown\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n        <img");

WriteLiteral(" data-bind=\"fieldImage : $type\"");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(" alt=\".\"");

WriteLiteral(" />\r\n        <!-- ko text : Name -->\r\n        <!-- /ko -->\r\n        <span");

WriteLiteral(" class=\"caret pull-right\"");

WriteLiteral("></span>\r\n    </a>\r\n    <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" data-bind=\"with : ");

            
            #line 14 "..\..\Areas\Sph\Views\EntityDefinition\_RuleFieldDropDown.cshtml"
                         Write(Model.Path);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"btn btn-link\"");

WriteLiteral(" data-bind=\"visible: Name() !== \'+ Field\',unwrapClick: $parent.editField.call($pa" +
"rent, $data, $parent.");

            
            #line 15 "..\..\Areas\Sph\Views\EntityDefinition\_RuleFieldDropDown.cshtml"
                                                                                                                                    Write(Model.Path);

            
            #line default
            #line hidden
WriteLiteral(")\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-edit\"");

WriteLiteral("></i>\r\n                Edit Field\r\n            </a>\r\n        </li>\r\n\r\n");

            
            #line 21 "..\..\Areas\Sph\Views\EntityDefinition\_RuleFieldDropDown.cshtml"
        
            
            #line default
            #line hidden
            
            #line 21 "..\..\Areas\Sph\Views\EntityDefinition\_RuleFieldDropDown.cshtml"
         foreach (var type in fieldTypes)
        {

            
            #line default
            #line hidden
WriteLiteral("            <li>\r\n                <a");

WriteLiteral(" class=\"btn btn-link\"");

WriteLiteral(" data-bind=\"unwrapClick: addField, field : \'");

            
            #line 24 "..\..\Areas\Sph\Views\EntityDefinition\_RuleFieldDropDown.cshtml"
                                                                              Write(type);

            
            #line default
            #line hidden
WriteLiteral("\', accessor : $data.");

            
            #line 24 "..\..\Areas\Sph\Views\EntityDefinition\_RuleFieldDropDown.cshtml"
                                                                                                       Write(Model.Path);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1081), Tuple.Create("\"", 1130)
            
            #line 25 "..\..\Areas\Sph\Views\EntityDefinition\_RuleFieldDropDown.cshtml"
, Tuple.Create(Tuple.Create("", 1087), Tuple.Create<System.Object, System.Int32>(string.Format("/images/{0}Field.png",type)
            
            #line default
            #line hidden
, 1087), false)
);

WriteLiteral(" class=\"pull-left\"");

WriteLiteral("/>\r\n                    + ");

            
            #line 26 "..\..\Areas\Sph\Views\EntityDefinition\_RuleFieldDropDown.cshtml"
                 Write(type);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </a>\r\n            </li>\r\n");

            
            #line 29 "..\..\Areas\Sph\Views\EntityDefinition\_RuleFieldDropDown.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    </ul>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
