#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sph/Views/Editor/_Toolbar.cshtml")]
    public partial class _Areas_Sph_Views_Editor__Toolbar_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Sph_Views_Editor__Toolbar_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<header");

WriteLiteral(" class=\"navbar navbar-static-top \"");

WriteLiteral(" id=\"top\"");

WriteLiteral(" role=\"banner\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" style=\"color: black;\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\"#header-navbar\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle navigation</span>\r\n                <i");

WriteLiteral(" class=\"fa fa-bars\"");

WriteLiteral("></i>\r\n            </button>\r\n            <a");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Code Editor</a>\r\n        </div>\r\n        <nav");

WriteLiteral(" id=\"header-navbar\"");

WriteLiteral(" class=\"collapse navbar-collapse\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(" style=\"background-color: white\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"nav navbar-nav navbar-right\"");

WriteLiteral(">\r\n\r\n                <li>\r\n                    <a");

WriteLiteral(" data-bind=\"click : save\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-save\"");

WriteLiteral("></i>Save</a>\r\n                </li>\r\n                <li>\r\n                    <" +
"a");

WriteLiteral(" data-bind=\"click : saveAndClose\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-arrow-circle-down\"");

WriteLiteral("></i>Save &amp; Close</a>\r\n                </li>\r\n                ");

WriteLiteral("\r\n                <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1225), Tuple.Create("\"", 1251)
            
            #line 25 "..\..\Areas\Sph\Views\Editor\_Toolbar.cshtml"
, Tuple.Create(Tuple.Create("", 1232), Tuple.Create<System.Object, System.Int32>(Url.Action("Help")
            
            #line default
            #line hidden
, 1232), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">Help</a></li>\r\n\r\n                <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(">View Snippets <b");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></b></a>\r\n                    <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(" id=\"snippets-list\"");

WriteLiteral(">\r\n                        <!-- ko foreach : snippets -->\r\n                      " +
"  <li><span");

WriteLiteral(" data-bind=\"text:title, attr :{title : note}\"");

WriteLiteral("></span></li>\r\n                        <!-- /ko -->\r\n                    </ul>\r\n " +
"               </li>\r\n\r\n                <li>\r\n                    <a");

WriteLiteral(" data-bind=\"click : function(){ window.close();}\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-times\"");

WriteLiteral(" style=\"margin-right: 5px\"");

WriteLiteral("></i>Discard &amp; Close</a>\r\n                </li>\r\n            </ul>\r\n\r\n\r\n\r\n   " +
"     </nav>\r\n\r\n    </div>\r\n</header>");

        }
    }
}
#pragma warning restore 1591
