#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Areas.Sph.Views.Editor
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sph/Views/Editor/_Toolbar.cshtml")]
    public partial class Toolbar : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Toolbar()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<nav");

WriteLiteral(" id=\"header-navbar\"");

WriteLiteral(" class=\"navbar navbar-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\"#bs-example-navbar-collapse-1\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle navigation</span>\r\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n        </button>\r\n        <a");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Code Editor</a>\r\n    </div>\r\n    <!-- Collect the nav links, forms, and other co" +
"ntent for toggling -->\r\n    <div");

WriteLiteral(" class=\"collapse navbar-collapse\"");

WriteLiteral(" id=\"bs-example-navbar-collapse-1\"");

WriteLiteral(">\r\n\r\n        <form");

WriteLiteral(" class=\"navbar-form navbar-left\"");

WriteLiteral(" role=\"search\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" data-bind=\"click : save\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-save\"");

WriteLiteral("></i>Save</button>\r\n            <button");

WriteLiteral(" data-bind=\"click : saveAndClose\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-arrow-circle-down\"");

WriteLiteral("></i>Save &amp; Close</button>\r\n            <button");

WriteLiteral(" data-bind=\"click : copy\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-copy\"");

WriteLiteral("></i>Copy               </button>\r\n            <button");

WriteLiteral(" data-bind=\"click : paste\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-paste\"");

WriteLiteral("></i>Paste</button>\r\n            <input");

WriteLiteral(" data-bind=\"value : searchText\"");

WriteLiteral(" type=\"search\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" style=\"width: 100px\"");

WriteLiteral(" />\r\n            <button");

WriteLiteral(" data-bind=\"click : search\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i>Search</button>\r\n            <button");

WriteLiteral(" data-bind=\"click : logs\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-clock-o\"");

WriteLiteral("></i>Logs</button>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Theme</label>\r\n                <select");

WriteLiteral(" style=\"width: 200px\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"theme\"");

WriteLiteral(">\r\n                    <optgroup");

WriteLiteral(" label=\"Light\"");

WriteLiteral(">\r\n                        <option");

WriteLiteral(" value=\"textmate\"");

WriteLiteral(">Textmate</option>\r\n                        <option");

WriteLiteral(" value=\"crimson_editor\"");

WriteLiteral(">Crimson</option>\r\n                    </optgroup>\r\n                    <optgroup" +
"");

WriteLiteral(" label=\"Dark\"");

WriteLiteral(">\r\n                        <option");

WriteLiteral(" value=\"monokai\"");

WriteLiteral(">Monokai</option>\r\n                        <option");

WriteLiteral(" value=\"twilight\"");

WriteLiteral(">Twilight</option>\r\n                    </optgroup>\r\n                </select>\r\n " +
"           </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Font size</label>\r\n                <select");

WriteLiteral(" style=\"width: 100px\"");

WriteLiteral(" id=\"font-size\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n");

            
            #line 39 "..\..\Areas\Sph\Views\Editor\_Toolbar.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 39 "..\..\Areas\Sph\Views\Editor\_Toolbar.cshtml"
                     for (int i = 10; i < 21; i++)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <option");

WriteAttribute("value", Tuple.Create(" value=\"", 2475), Tuple.Create("\"", 2485)
            
            #line 41 "..\..\Areas\Sph\Views\Editor\_Toolbar.cshtml"
, Tuple.Create(Tuple.Create("", 2483), Tuple.Create<System.Object, System.Int32>(i
            
            #line default
            #line hidden
, 2483), false)
);

WriteLiteral(">");

            
            #line 41 "..\..\Areas\Sph\Views\Editor\_Toolbar.cshtml"
                                      Write(i);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 42 "..\..\Areas\Sph\Views\Editor\_Toolbar.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </select>\r\n            </div>\r\n\r\n        </form>\r\n        <ul");

WriteLiteral(" class=\"nav navbar-nav navbar-right\"");

WriteLiteral(">\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2657), Tuple.Create("\"", 2683)
            
            #line 48 "..\..\Areas\Sph\Views\Editor\_Toolbar.cshtml"
, Tuple.Create(Tuple.Create("", 2664), Tuple.Create<System.Object, System.Int32>(Url.Action("Help")
            
            #line default
            #line hidden
, 2664), false)
);

WriteLiteral(" data-target=\"#help\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(">Help</a></li>\r\n            <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(">Insert Snippets <b");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></b></a>\r\n                <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(" id=\"snippets-list\"");

WriteLiteral(">\r\n                    <!-- ko foreach : snippets -->\r\n\r\n                    <li>" +
"<a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-bind=\"text:title\"");

WriteLiteral("></a></li>\r\n\r\n                    <!-- /ko -->\r\n                    <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-bind=\"click: openSnippetEditor\"");

WriteLiteral(">Snippets Editor</a></li>\r\n                </ul>\r\n            </li>\r\n        </ul" +
">\r\n    </div><!-- /.navbar-collapse -->\r\n\r\n\r\n    <form");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        </div>\r\n    </form>\r\n    <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" style=\"background-color: white\"");

WriteLiteral(" id=\"help\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"myModalLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</button>\r\n                    <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"myModalLabel\"");

WriteLiteral(">Modal title</h4>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                    ...\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Close</button>\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">Save changes</button>\r\n                </div>\r\n            </div><!-- /.modal-co" +
"ntent -->\r\n        </div><!-- /.modal-dialog -->\r\n    </div><!-- /.modal -->\r\n</" +
"nav>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
