//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.SqlRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SettingId { get; set; }
        public string Data { get; set; }
        public string UserName { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public string ChangedBy { get; set; }
    }
}
