#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Areas.App.Views.ReportDefinitionEdit
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/App/Views/ReportDefinitionEdit/_ConfigurationDatasource.cshtml")]
    public partial class ConfigurationDatasource : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ConfigurationDatasource()
        {
        }
        public override void Execute()
        {
WriteLiteral("<form class=\"form-horizontal\" data-bind=\"with: DataSource\">\r\n    <div class=\"form" +
"-group\">\r\n        <label for=\"data-source-entity\" class=\"col-lg-2\">Entity</label" +
">\r\n        <div class=\"col-lg-9\">\r\n            <select class=\"form-control\" data" +
"-bind=\"value: EntityName, options: $root.entities, optionsCaption : \'[Select Ent" +
"ity]\'\" id=\"data-source-entity\" name=\"Entity\"></select>\r\n        </div>\r\n    </di" +
"v>\r\n    <div class=\"form-group\">\r\n    </div>\r\n    <table class=\"table table-stri" +
"ped\" data-bind=\"scroll : 5\">\r\n        <thead>\r\n            <tr>\r\n               " +
" <th>Field</th>\r\n                <th>Operator</th>\r\n                <th>Value</t" +
"h>\r\n                <th></th>\r\n            </tr>\r\n        </thead>\r\n        <tbo" +
"dy data-bind=\"foreach: ReportFilterCollection\">\r\n            <tr>\r\n             " +
"   <td>\r\n                    <select class=\"input-datasource-fieldname form-cont" +
"rol\" data-bind=\"value: FieldName, options: $root.filterableEntityColumns, option" +
"sText: \'Name\', optionsValue: \'Name\'\"></select>\r\n                </td>\r\n         " +
"       <td>\r\n                    <select data-bind=\"value: Operator\" class=\"inpu" +
"t-datasource-operator form-control\">\r\n                        <option value=\"Eq\"" +
">=</option>\r\n                        <option value=\"Neq\">!=</option>\r\n          " +
"              <option value=\"Le\">&lt;=</option>\r\n                        <option" +
" value=\"Lt\">&lt;</option>\r\n                        <option value=\"Ge\">&gt;=</opt" +
"ion>\r\n                        <option value=\"Gt\">&gt;</option>\r\n                " +
"        <option value=\"Substringof\">Contains</option>\r\n                        <" +
"option value=\"StartsWith\">Starts with</option>\r\n                        <option " +
"value=\"EndsWith\">Ends with</option>\r\n                        <option value=\"NotC" +
"ontains\">Not Substringof</option>\r\n                        <option value=\"NotSta" +
"rtsWith\">Not StartsWith</option>\r\n                        <option value=\"NotEnds" +
"With\">Not EndsWith</option>\r\n\r\n                    </select>\r\n                </" +
"td>\r\n                <td>\r\n                    <input class=\"input-datasource-va" +
"lue form-control\" type=\"text\" data-bind=\"value: Value\" />\r\n                </td>" +
"\r\n                <td>\r\n                    <a href=\"#\" data-bind=\"click: $root." +
"removeFilter\"><i class=\"fa fa-times\"></i></a>\r\n                </td>\r\n          " +
"  </tr>\r\n        </tbody>\r\n    </table>\r\n    <a class=\"btn-link btn\" href=\"#\" da" +
"ta-bind=\"click: $root.addFilter\">\r\n        <i class=\"fa fa-plus-circle\"></i>\r\n  " +
"      Add a query filter\r\n    </a>\r\n    <div class=\"form-group\">\r\n        <label" +
" for=\"data-source-query\" class=\"control-label\">Query</label>\r\n        <div class" +
"=\"controls\">\r\n            <textarea placeholder=\"Write your custom SQL query\" cl" +
"ass=\"form-control\" rows=\"8\" data-bind=\"value: Query\" id=\"data-source-query\" name" +
"=\"Query\"></textarea>\r\n        </div>\r\n    </div>\r\n</form>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
