#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Areas.App.Views.ReportDefinitionEdit
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/App/Views/ReportDefinitionEdit/_DataGridDesignerContextAction.cshtml")]
    public partial class DataGridDesignerContextAction : System.Web.Mvc.WebViewPage<dynamic>
    {
        public DataGridDesignerContextAction()
        {
        }
        public override void Execute()
        {
WriteLiteral("<section class=\"context-action-panel\" data-bind=\"visible: isSelected\">\r\n    <butt" +
"on class=\"btn btn-link btn-context-action\">\r\n        <i class=\"fa fa-chevron-cir" +
"cle-right\"></i>\r\n    </button>\r\n\r\n    <div class=\"context-action\" style=\"width: " +
"720px\">\r\n        <div class=\"modal-header\">\r\n            <button type=\"button\" c" +
"lass=\"close\" data-dismiss=\"modal\">&times;</button>\r\n            <span>DataGrid P" +
"roperties</span>\r\n        </div>\r\n        <table class=\"table table-striped\">\r\n " +
"           <colgroup>\r\n                <col style=\"width: 240px\" />\r\n           " +
"     <col style=\"width: 200px\" />\r\n                <col style=\"width: 100px\" />\r" +
"\n                <col style=\"width: 200px\" />\r\n            </colgroup>\r\n        " +
"    <thead>\r\n                <tr>\r\n                    <th>Expression</th>\r\n    " +
"                <th>Header</th>\r\n                    <th>Format</th>\r\n          " +
"          <th>Footer</th>\r\n                    <th></th>\r\n                </tr>\r" +
"\n            </thead>\r\n            <tbody data-bind=\"foreach: DataGridColumnColl" +
"ection\">\r\n                <tr>\r\n                    <td>\r\n                      " +
"  <input class=\"input-datagrid-column-expression form-control \" data-bind=\"kendo" +
"ComboBox: Expression, source: $root.dataGridColumnOptions\" />\r\n                 " +
"   </td>\r\n                    <td><input type=\"text\" class=\"input-datagrid-colum" +
"n-header form-control\" data-bind=\"value: Header\" /></td>\r\n                    <t" +
"d>\r\n                        <input class=\"form-control\" data-bind=\"kendoComboBox" +
":Format, source :ko.observableArray([\'{0:d}\',\'{0:F2}\',\'{0:g}\', \'{0:c}\'])\" />\r\n  " +
"                  </td>\r\n                    <td>\r\n                        <inpu" +
"t type=\"text\" class=\"input-datagrid-column-footer form-control\" data-bind=\"value" +
": FooterExpression\" />\r\n                    </td>\r\n                    <td><a hr" +
"ef=\"#\" data-bind=\"click : $parent.removeColumn.call($parent,$data)\"><i class=\"fa" +
" fa-times\"></i></a></td>\r\n                </tr>\r\n            </tbody>\r\n        <" +
"/table>\r\n\r\n\r\n        <a class=\"btn btn-link\" data-bind=\"click : addColumn\">\r\n   " +
"         <i class=\"fa fa-plus-circle\"></i>\r\n\r\n            Add a column\r\n        " +
"</a>\r\n        <table class=\"table table-striped\">\r\n            <colgroup>\r\n     " +
"           <col style=\"width: 100px\" />\r\n                <col style=\"width: 100p" +
"x\" />\r\n                <col style=\"width: 30px\" />\r\n                <col style=\"" +
"width: 100px\" />\r\n            </colgroup>\r\n            <thead>\r\n                " +
"<tr>\r\n                    <th>Column</th>\r\n                    <th>Text</th>\r\n  " +
"                  <th>Footer</th>\r\n                    <th></th>\r\n              " +
"  </tr>\r\n            </thead>\r\n            <tbody data-bind=\"foreach: DataGridGr" +
"oupDefinitionCollection\">\r\n                <tr>\r\n                    <td>\r\n     " +
"                   <input class=\"input-datagrid-group-column form-control \" data" +
"-bind=\"kendoComboBox: Column, source: $root.columnOptions\" />\r\n                 " +
"   </td>\r\n                    <td><input type=\"text\" class=\"form-control input-d" +
"atagrid-group-expression\" data-bind=\"value: Expression\" /></td>\r\n               " +
"     <td>\r\n                        <input class=\"form-control input-datagrid-gro" +
"up-footer\" data-bind=\"value: FooterExpression\" />\r\n                    </td>\r\n  " +
"                  <td><a href=\"#\" data-bind=\"click: $parent.removeDataGridGroupD" +
"efinition.call($parent, $data)\"><i class=\"fa fa-times\"></i></a></td>\r\n          " +
"      </tr>\r\n            </tbody>\r\n        </table>\r\n\r\n        <a class=\"btn btn" +
"-link\" data-bind=\"click: addDataGridGroupDefinition\">\r\n            <i class=\"fa " +
"fa-plus-circle\"></i>\r\n            Add a group\r\n        </a>\r\n\r\n        <a class=" +
"\"btn btn-link pull-right\" data-bind=\"click: $root.removeReportItem\">\r\n          " +
"  <i class=\"fa fa-times\"></i>\r\n            Remove\r\n        </a>\r\n\r\n\r\n    </div>\r" +
"\n</section>\r\n");


        }
    }
}
#pragma warning restore 1591
