#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Areas.App.Views.EntityFormRenderer.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Bespoke.Sph.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/App/Views/EntityFormRenderer/EditorTemplates/Button.cshtml")]
    public partial class _Button : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.Button>
    {
        public _Button()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\Button.cshtml"
  
    var command = Model.UseClick ? "click" : "command";

            
            #line default
            #line hidden
WriteLiteral("\r\n<button");

WriteLiteral(" data-bind=\"");

            
            #line 5 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\Button.cshtml"
              Write(command);

            
            #line default
            #line hidden
WriteLiteral(" : $root.");

            
            #line 5 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\Button.cshtml"
                               Write(Model.CommandName);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("class", Tuple.Create(" class=\"", 153), Tuple.Create("\"", 176)
            
            #line 5 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\Button.cshtml"
, Tuple.Create(Tuple.Create("", 161), Tuple.Create<System.Object, System.Int32>(Model.CssClass
            
            #line default
            #line hidden
, 161), false)
);

WriteLiteral(">");

            
            #line 5 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\Button.cshtml"
                                                                           Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

        }
    }
}
#pragma warning restore 1591
