#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Areas.App.Views.EntityFormRenderer.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Bespoke.Sph.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/App/Views/EntityFormRenderer/EditorTemplates/FileUploadElement.cshtml")]
    public partial class _FileUploadElement : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.FileUploadElement>
    {
        public _FileUploadElement()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
  
    var required = Model.IsRequired ? "required" : null;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 5 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
 if (Model.IsCompact)
{

            
            #line default
            #line hidden
WriteLiteral("    <input ");

            
            #line 7 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
      Write(required);

            
            #line default
            #line hidden
WriteLiteral(" class=\"");

            
            #line 7 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
                        Write(Model.CssClass + " form-control " + Model.Size);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");

            
            #line 7 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
                                                                                 Write(Model.Tooltip);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n           data-bind=\"");

            
            #line 8 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
                  Write(Html.Raw(Model.GetKnockoutBindingExpression()));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n           id=\"");

            
            #line 9 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
          Write(Model.ElementId);

            
            #line default
            #line hidden
WriteLiteral("\" type=\"file\" name=\"files\" />\r\n");

            
            #line 10 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
}
else
{


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" data-bind=\"visible:");

            
            #line 14 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
                       Write(Model.Visible);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <label");

WriteAttribute("for", Tuple.Create(" for=\"", 468), Tuple.Create("\"", 490)
            
            #line 15 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
, Tuple.Create(Tuple.Create("", 474), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 474), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 491), Tuple.Create("\"", 519)
            
            #line 15 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
, Tuple.Create(Tuple.Create("", 499), Tuple.Create<System.Object, System.Int32>(Model.LabelCssClass
            
            #line default
            #line hidden
, 499), false)
);

WriteLiteral(">");

            
            #line 15 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
                                                              Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 555), Tuple.Create("\"", 588)
            
            #line 16 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
, Tuple.Create(Tuple.Create("", 563), Tuple.Create<System.Object, System.Int32>(Model.InputPanelCssClass
            
            #line default
            #line hidden
, 563), false)
);

WriteLiteral(">\r\n            <input ");

            
            #line 17 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
              Write(required);

            
            #line default
            #line hidden
WriteLiteral(" class=\"");

            
            #line 17 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
                                Write(Model.CssClass + " form-control " + Model.Size);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");

            
            #line 17 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
                                                                                         Write(Model.Tooltip);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                   data-bind=\"");

            
            #line 18 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
                          Write(Html.Raw(Model.GetKnockoutBindingExpression()));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                   id=\"");

            
            #line 19 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
                  Write(Model.ElementId);

            
            #line default
            #line hidden
WriteLiteral("\" type=\"file\" name=\"files\" />\r\n        </div>\r\n");

            
            #line 21 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
        
            
            #line default
            #line hidden
            
            #line 21 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
         if (!string.IsNullOrWhiteSpace(Model.HelpText))
        {

            
            #line default
            #line hidden
WriteLiteral("            <span");

WriteLiteral(" class=\"help-block\"");

WriteLiteral(">");

            
            #line 23 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
                                Write(Model.HelpText);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 24 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 26 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\FileUploadElement.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
