#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Areas.App.Views.EntityFormRenderer.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Bespoke.Sph.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/App/Views/EntityFormRenderer/EditorTemplates/NumberTextBox.cshtml")]
    public partial class _NumberTextBox : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.NumberTextBox>
    {
        public _NumberTextBox()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
 if (Model.IsCompact)
{

            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteAttribute("step", Tuple.Create(" step=\"", 77), Tuple.Create("\"", 95)
            
            #line 4 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 84), Tuple.Create<System.Object, System.Int32>(Model.Step
            
            #line default
            #line hidden
, 84), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 96), Tuple.Create("\"", 152)
            
            #line 4 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 104), Tuple.Create<System.Object, System.Int32>(Model.CssClass + " form-control "+ Model.Size
            
            #line default
            #line hidden
, 104), false)
);

WriteAttribute("title", Tuple.Create("\r\n           title=\"", 153), Tuple.Create("\"", 187)
            
            #line 5 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 173), Tuple.Create<System.Object, System.Int32>(Model.Tooltip
            
            #line default
            #line hidden
, 173), false)
);

WriteLiteral(" data-bind=\"");

            
            #line 5 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
                                         Write(Html.Raw(Model.GetKnockoutBindingExpression()));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create("\r\n           id=\"", 250), Tuple.Create("\"", 283)
            
            #line 6 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 267), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 267), false)
);

WriteLiteral(" type=\"number\"");

WriteAttribute("name", Tuple.Create(" name=\"", 298), Tuple.Create("\"", 316)
            
            #line 6 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 305), Tuple.Create<System.Object, System.Int32>(Model.Path
            
            #line default
            #line hidden
, 305), false)
);

WriteLiteral(" />\r\n");

            
            #line 7 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
}
else
{


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <label");

WriteAttribute("for", Tuple.Create(" for=\"", 380), Tuple.Create("\"", 402)
            
            #line 12 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 386), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 386), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 403), Tuple.Create("\"", 431)
            
            #line 12 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 411), Tuple.Create<System.Object, System.Int32>(Model.LabelCssClass
            
            #line default
            #line hidden
, 411), false)
);

WriteLiteral(">");

            
            #line 12 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
                                                              Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 467), Tuple.Create("\"", 500)
            
            #line 13 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 475), Tuple.Create<System.Object, System.Int32>(Model.InputPanelCssClass
            
            #line default
            #line hidden
, 475), false)
);

WriteLiteral(">\r\n            <input");

WriteAttribute("step", Tuple.Create(" step=\"", 522), Tuple.Create("\"", 540)
            
            #line 14 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 529), Tuple.Create<System.Object, System.Int32>(Model.Step
            
            #line default
            #line hidden
, 529), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 541), Tuple.Create("\"", 597)
            
            #line 14 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 549), Tuple.Create<System.Object, System.Int32>(Model.CssClass + " form-control "+ Model.Size
            
            #line default
            #line hidden
, 549), false)
);

WriteAttribute("title", Tuple.Create("\r\n                   title=\"", 598), Tuple.Create("\"", 640)
            
            #line 15 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 626), Tuple.Create<System.Object, System.Int32>(Model.Tooltip
            
            #line default
            #line hidden
, 626), false)
);

WriteLiteral(" data-bind=\"");

            
            #line 15 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
                                                 Write(Html.Raw(Model.GetKnockoutBindingExpression()));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create("\r\n                   id=\"", 703), Tuple.Create("\"", 744)
            
            #line 16 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 728), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 728), false)
);

WriteLiteral(" type=\"number\"");

WriteAttribute("name", Tuple.Create(" name=\"", 759), Tuple.Create("\"", 777)
            
            #line 16 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 766), Tuple.Create<System.Object, System.Int32>(Model.Path
            
            #line default
            #line hidden
, 766), false)
);

WriteLiteral(" />\r\n        </div>\r\n");

            
            #line 18 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
        
            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
         if (!string.IsNullOrWhiteSpace(Model.HelpText))
        {

            
            #line default
            #line hidden
WriteLiteral("            <span");

WriteLiteral(" class=\"help-block\"");

WriteLiteral(">");

            
            #line 20 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
                                Write(Model.HelpText);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 21 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 23 "..\..\Areas\App\Views\EntityFormRenderer\EditorTemplates\NumberTextBox.cshtml"
}
            
            #line default
            #line hidden
WriteLiteral("  ");

        }
    }
}
#pragma warning restore 1591
