#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Areas.App.Views.Users
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/App/Views/Users/Html.cshtml")]
    public partial class Html : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Html()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Areas\App\Views\Users\Html.cshtml"
  
    ViewBag.Title = "Users";
    Layout = "~/Views/Shared/_Layout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("<h1>Users Management</h1>\r\n\r\n<div class=\"row\">\r\n    <ul class=\"nav nav-tabs\">\r\n  " +
"      <li class=\"active\">\r\n            <a href=\"#user-tab\" data-toggle=\"tab\">Use" +
"rs</a>\r\n        </li>\r\n        <li>\r\n            <a href=\"#designation-tab\" data" +
"-toggle=\"tab\">Designations</a>\r\n        </li>\r\n        <li>\r\n            <a href" +
"=\"#department-tab\" data-toggle=\"tab\">Departments</a>\r\n        </li>\r\n    </ul>\r\n" +
"\r\n    <div class=\"tab-content\">\r\n        <div id=\"user-tab\" class=\"tab-pane acti" +
"ve\">\r\n            <div class=\"search-panel row\" data-bind=\"with: searchTerm\">\r\n " +
"               <form class=\"form-inline col-lg-12\">\r\n                    <div cl" +
"ass=\"row\">\r\n                        <div class=\"form-group col-lg-3\">\r\n         " +
"                   <label class=\"\">Department</label>\r\n                        <" +
"/div>\r\n                        <div class=\"form-group\">\r\n                       " +
"     <select class=\"form-control col-lg-3\" data-bind=\"options: $root.departmentO" +
"ptions, value: department, optionsText: \'Name\', optionsValue: \'Name\'\"></select>\r" +
"\n                        </div>\r\n                        <div class=\"form-group\"" +
">\r\n                            <label class=\"control-label col-lg-1 sr-only\">Kat" +
"a Kunci</label>\r\n                            <input placeholder=\"Keywords\" class" +
"=\"form-control col-lg-2\" type=\"text\" data-bind=\"value: keyword\" required />\r\n   " +
"                     </div>\r\n                        <div class=\"form-group col-" +
"lg-2 pull-right\">\r\n                            <button type=\"submit\" class=\"btn " +
"btn-default\" id=\"search-btn\">\r\n                                <i class=\"fa fa-s" +
"earch pull-left\"></i>\r\n                                Search\r\n                 " +
"           </button>\r\n                        </div>\r\n\r\n                    </di" +
"v>\r\n\r\n                </form>\r\n            </div>\r\n            <div>\r\n          " +
"      <table class=\"table table-striped\" data-bind=\"serverPaging: { entity: \'Use" +
"rProfile\', query: \'UserProfileId gt 0\', list: profiles, map: map }\">\r\n          " +
"          <thead>\r\n                        <tr>\r\n                            <th" +
">UserName</th>\r\n                            <th>Full name</th>\r\n                " +
"            <th>Department</th>\r\n                            <th>Designation</th" +
">\r\n                            <th>Email</th>\r\n                            <th>P" +
"assword</th>\r\n                        </tr>\r\n                    </thead>\r\n     " +
"               <tbody data-bind=\"foreach: profiles\">\r\n                        <t" +
"r>\r\n                            <td>\r\n                                <a data-to" +
"ggle=\"modal\" href=\"#user-details-modal\" data-bind=\"click: $root.editCommand\">\r\n " +
"                                   <i class=\"fa fa-user\"></i>\r\n                 " +
"                   <!-- ko text: UserName-->\r\n                                  " +
"  <!-- /ko-->\r\n                                </a>\r\n\r\n                         " +
"   </td>\r\n                            <td data-bind=\"text: FullName\"></td>\r\n    " +
"                        <td data-bind=\"text: Department\"></td>\r\n                " +
"            <td data-bind=\"text: Designation\"></td>\r\n                           " +
" <td data-bind=\"text: Email\"></td>\r\n                            <td>\r\n          " +
"                      <a data-toggle=\"modal\" href=\"#user-change-password\" data-b" +
"ind=\"click: $root.resetPasswordCommand\">Reset</a>\r\n                            <" +
"/td>\r\n                        </tr>\r\n                    </tbody>\r\n             " +
"   </table>\r\n            </div>\r\n        </div>\r\n        <div id=\"designation-ta" +
"b\" class=\"tab-pane \">\r\n            <!--ko compose:\'viewmodels/_users.designation" +
"\' -->\r\n            <!--/ko-->\r\n        </div>\r\n        <div id=\"department-tab\" " +
"class=\"tab-pane \">\r\n            <!--ko compose:\'viewmodels/_users.department\' --" +
">\r\n            <!--/ko-->\r\n        </div>\r\n    </div>\r\n</div>\r\n<!--ko compose:\'_" +
"user.add.html\' -->\r\n<!--/ko-->\r\n<!--ko compose:\'_user.change.password.html\' -->\r" +
"\n<!--/ko-->");


        }
    }
}
#pragma warning restore 1591
