#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Views.Shared.DisplayTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/ImageElement.cshtml")]
    public partial class ImageElement_ : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.ImageElement>
    {
        public ImageElement_()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
  
    var path = string.Format("'/sph/image/store/' + {0}()", this.Model.Path);
    var width = Model.Width.HasValue ? "width=\"" + Model.Width.Value + "\"" : "";
    var height = Model.Height.HasValue ? "height=\"" + Model.Height.Value + "\"" : "";

    if (string.IsNullOrWhiteSpace(Model.Enable))
    {
        Model.Enable = "true";
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 13 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
 if (!Model.IsCompact)
{

            
            #line default
            #line hidden
WriteLiteral("    <label");

WriteAttribute("class", Tuple.Create(" class=\"", 435), Tuple.Create("\"", 474)
, Tuple.Create(Tuple.Create("", 443), Tuple.Create("col-md-", 443), true)
            
            #line 15 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
, Tuple.Create(Tuple.Create("", 450), Tuple.Create<System.Object, System.Int32>(Model.LabelColMd ?? 4
            
            #line default
            #line hidden
, 450), false)
);

WriteLiteral(">");

            
            #line 15 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
                                              Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

            
            #line 16 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<img");

WriteAttribute("alt", Tuple.Create(" alt=\"", 505), Tuple.Create("\"", 523)
            
            #line 17 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
, Tuple.Create(Tuple.Create("", 511), Tuple.Create<System.Object, System.Int32>(Model.Label
            
            #line default
            #line hidden
, 511), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 524), Tuple.Create("\"", 546)
            
            #line 17 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
, Tuple.Create(Tuple.Create("", 532), Tuple.Create<System.Object, System.Int32>(Model.Tooltip
            
            #line default
            #line hidden
, 532), false)
);

WriteLiteral(" ");

            
            #line 17 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
                                          Write(width);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 17 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
                                                 Write(height);

            
            #line default
            #line hidden
WriteLiteral(" data-bind=\"attr : {\'src\':");

            
            #line 17 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
                                                                                  Write(Html.Raw(path));

            
            #line default
            #line hidden
WriteLiteral("}, visible:");

            
            #line 17 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
                                                                                                            Write(Html.Raw(Model.Visible));

            
            #line default
            #line hidden
WriteLiteral("\" />");

        }
    }
}
#pragma warning restore 1591
