#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Views.Shared.DisplayTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/ImageElement.cshtml")]
    public partial class ImageElement : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.ImageElement>
    {
        public ImageElement()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
 if (string.IsNullOrWhiteSpace(Model.Enable))
{
    Model.Enable = "true";
}
            
            #line default
            #line hidden

            
            #line 5 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
   
    var path = string.Format("'/sph/image/store/' + {0}()", this.Model.Path);
 

            
            #line default
            #line hidden
WriteLiteral("<div class=\"form-group\">\r\n    <label class=\"col-md-");


            
            #line 9 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
                     Write(Model.LabelColMd ?? 4);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 9 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
                                              Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n    <img alt=\"");


            
            #line 10 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
         Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");


            
            #line 10 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
                              Write(Model.Tooltip);

            
            #line default
            #line hidden
WriteLiteral("\" width=\"");


            
            #line 10 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
                                                     Write(Model.Width);

            
            #line default
            #line hidden
WriteLiteral("\" height=\"");


            
            #line 10 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
                                                                           Write(Model.Height);

            
            #line default
            #line hidden
WriteLiteral("\" data-bind=\"attr : {\'src\':");


            
            #line 10 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
                                                                                                                   Write(Html.Raw(path));

            
            #line default
            #line hidden
WriteLiteral("}, visible:");


            
            #line 10 "..\..\Views\Shared\DisplayTemplates\ImageElement.cshtml"
                                                                                                                                             Write(Html.Raw(Model.Visible));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n</div>");


        }
    }
}
#pragma warning restore 1591
