#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/TextBox.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_TextBox_cshtml_ : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.TextBox>
    {
        public _Views_Shared_DisplayTemplates_TextBox_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\DisplayTemplates\TextBox.cshtml"
 if (Model.IsCompact)
{

            
            #line default
            #line hidden
WriteLiteral("    <span");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(" data-bind=\"text: ");

            
            #line 5 "..\..\Views\Shared\DisplayTemplates\TextBox.cshtml"
                                       Write(Model.Path);

            
            #line default
            #line hidden
WriteLiteral(", visible:");

            
            #line 5 "..\..\Views\Shared\DisplayTemplates\TextBox.cshtml"
                                                            Write(Model.Visible);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></span>\r\n");

            
            #line 6 "..\..\Views\Shared\DisplayTemplates\TextBox.cshtml"

}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" data-bind=\"visible:");

            
            #line 10 "..\..\Views\Shared\DisplayTemplates\TextBox.cshtml"
                                          Write(Html.Raw(Model.Visible));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">");

            
            #line 11 "..\..\Views\Shared\DisplayTemplates\TextBox.cshtml"
                           Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n        <span");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(" data-bind=\"text: ");

            
            #line 12 "..\..\Views\Shared\DisplayTemplates\TextBox.cshtml"
                                           Write(Model.Path);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></span>\r\n    </div>\r\n");

            
            #line 14 "..\..\Views\Shared\DisplayTemplates\TextBox.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
