#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Areas.Sph.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sph/Views/Account/_Slider.cshtml")]
    public partial class Slider : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Slider()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"col-lg-4 login-slider col-lg-offset-1 visible-lg\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"this-carousel-id\"");

WriteLiteral(" class=\"carousel slide\"");

WriteLiteral(">\r\n        <!-- class of slide for animation -->\r\n        <div");

WriteLiteral(" class=\"carousel-inner\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"item active\"");

WriteLiteral(">\r\n                <!-- class of active since it\'s the first item -->\r\n          " +
"      <img");

WriteLiteral(" src=\"/Images/offices.png\"");

WriteLiteral(" alt=\"image\"");

WriteLiteral(" />\r\n                <div");

WriteLiteral(" class=\"carousel-caption\"");

WriteLiteral(">\r\n                    <h2>Ruang Pejabat & Komersil</h2>\r\n                    <p>" +
"\r\n                        Penyewaan ruang komersil dan ruang pejabat\r\n          " +
"          </p>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"/Images/courts.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" />\r\n                <div");

WriteLiteral(" class=\"carousel-caption\"");

WriteLiteral(">\r\n                    <h2>Dewan & Gelanggang</h2>\r\n                    <p>Tempah" +
"an jangka pendek untuk majlis dan riada</p>\r\n                </div>\r\n           " +
" </div>\r\n            <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"/Images/quarters.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" />\r\n                <div");

WriteLiteral(" class=\"carousel-caption\"");

WriteLiteral(">\r\n                    <h2>Kuarters</h2>\r\n                    <p>Penginapan kakit" +
"angan</p>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"/Images/hotel.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" />\r\n                <div");

WriteLiteral(" class=\"carousel-caption\"");

WriteLiteral(@">
                    <h2>Rumah Peranginan</h2>
                    <p>Rumah penginapan dan peranginan untuk kakitangan</p>
                </div>
            </div>
        </div><!-- /.carousel-inner -->
        <!--  Next and Previous controls below
            href values must reference the id for this carousel -->
        <a");

WriteLiteral(" class=\"carousel-control left\"");

WriteLiteral(" href=\"#this-carousel-id\"");

WriteLiteral(" data-slide=\"prev\"");

WriteLiteral(">&lsaquo;</a>\r\n        <a");

WriteLiteral(" class=\"carousel-control right\"");

WriteLiteral(" href=\"#this-carousel-id\"");

WriteLiteral(" data-slide=\"next\"");

WriteLiteral(">&rsaquo;</a>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
