#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Areas.Sph.Views.App
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Sph\Views\App\ReportDefinitionExecuteJs.cshtml"
    using Newtonsoft.Json;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sph/Views/App/ReportDefinitionExecuteJs.cshtml")]
    public partial class ReportDefinitionExecuteJs : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.ReportDefinition>
    {
        public ReportDefinitionExecuteJs()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Sph\Views\App\ReportDefinitionExecuteJs.cshtml"
  
    Layout = null;
    var datasourceJson = JsonConvert.SerializeObject(Model.DataSource);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" data-script=\"true\"");

WriteLiteral(">\r\n    define([\'services/datacontext\'], function (context) {\r\n        var isBusy " +
"= ko.observable(false),\r\n            id = 0,\r\n            activate = function (r" +
"outeData) {\r\n                id = parseInt(routeData.id);\r\n\r\n                var" +
" query = String.format(\"ReportDefinitionId eq {0}\", id),\r\n                    tc" +
"s = new $.Deferred();\r\n\r\n\r\n                context.loadOneAsync(\"ReportDefinitio" +
"n\", query)\r\n                    .done(vm.rdl)\r\n                    .done(tcs.res" +
"olve);\r\n\r\n                return tcs.promise();\r\n            },\r\n            vie" +
"wAttached = function () {\r\n                $(\'#parameters-dialog\').modal();\r\n   " +
"         },\r\n            exportCommand = function () {\r\n\r\n            },\r\n      " +
"      print = function () {\r\n\r\n            },\r\n            showParameterDialog =" +
" function () {\r\n                $(\'#parameters-dialog\').modal();\r\n              " +
"  var tcs = new $.Deferred();\r\n                setTimeout(tcs.resolve, 500);\r\n  " +
"              return tcs.promise();\r\n            },\r\n            execute = funct" +
"ion () {\r\n                var $layout = $(\'#report-layout-panel\');\r\n            " +
"    $layout.html(\'<img src=\"/Images/spinner-md.gif\" alt=\"loading\" class=\"absolut" +
"e-center\" />\');\r\n\r\n                NProgress.start();\r\n                var tcs =" +
" new $.Deferred();\r\n                var data = ko.mapping.toJSON(vm.datasource);" +
"\r\n                $.post(\"/App/ReportDefinitionExecuteHtml/\" + id, data, \"html\")" +
"\r\n                    .done(function (html) {\r\n                        NProgress" +
".done();\r\n                        $layout.html(html);\r\n                        t" +
"cs.resolve(true);\r\n                    });\r\n\r\n                return tcs.promise" +
"();\r\n            };\r\n\r\n\r\n        var vm = {\r\n            isBusy: isBusy,\r\n      " +
"      activate: activate,\r\n            viewAttached: viewAttached,\r\n            " +
"rdl: ko.observable(),\r\n            datasource: ko.mapping.fromJSON(\'");

            
            #line 63 "..\..\Areas\Sph\Views\App\ReportDefinitionExecuteJs.cshtml"
                                        Write(Html.Raw(datasourceJson));

            
            #line default
            #line hidden
WriteLiteral(@"'),
            executeCommand: execute,
            toolbar: {
                exportCommand: exportCommand,
                printCommand: print,
                commands: ko.observableArray([{
                    command: showParameterDialog,
                    caption: 'Show Parameter',
                    icon: 'icon-keyboard'

                }])
            }

        };
        return vm;
    });
</script>
");

        }
    }
}
#pragma warning restore 1591
