USE [Sph]
IF OBJECT_ID('Sph.Contract', 'U') IS NOT NULL
  DROP TABLE Sph.[Contract]
GO

CREATE TABLE [Sph].[Contract]
(
	 [ContractId] INT PRIMARY KEY IDENTITY(1,1)	
	,[ReferenceNo] VARCHAR(255) NULL
	,[Title] VARCHAR(255) NULL
	,[Status] VARCHAR(255) NOT NULL
	,[TenantName] VARCHAR(255) NOT NULL
	,[TenantIdSsmNo] VARCHAR(255) NOT NULL
	,[TenantRegistrationNo] VARCHAR(255) NOT NULL
	,[StartDate] SMALLDATETIME  NOT NULL
	,[EndDate] SMALLDATETIME NOT NULL
	,[SpaceId] INT NOT NULL
	,[SpaceRegistrationNo] VARCHAR(255) NOT NULL
	,[Data] XML NOT NULL
	,[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[CreatedBy] VARCHAR(255) NULL
	,[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[ChangedBy] VARCHAR(255) NULL
)
GO 