IF OBJECT_ID('Sph.Message', 'U') IS NOT NULL
  DROP TABLE Sph.[Message]
GO

CREATE TABLE [Sph].[Message]
(
	 [MessageId] INT PRIMARY KEY IDENTITY(1,1)		 
	,[Subject] VARCHAR (255) NULL
	,[IsRead] BIT NOT NULL
	,[Body]	VARCHAR (4000) NOT NULL
	,[UserName] VARCHAR(255) NOT NULL
	,[Json] VARCHAR(MAX) NOT NULL
	,[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[CreatedBy] VARCHAR(255) NULL
	,[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[ChangedBy] VARCHAR(255) NULL
)
GO 
ALTER TABLE  [Sph].[Message]
ADD [Json] VARCHAR(MAX) NULL