USE [Sph]
IF OBJECT_ID('Sph.Land', 'U') IS NOT NULL
  DROP TABLE Sph.Land
GO

CREATE TABLE Sph.Land
(
	 [LandId] INT PRIMARY KEY IDENTITY(1,1)
	,[Data] XML NOT NULL
	,[Lot] VARCHAR(255) NULL
	,[Location] VARCHAR(255) NULL
	,[Title] VARCHAR(255) NULL
	,[Size] float NULL
	,[SheetNo] VARCHAR(255) NULL
	,[Status] VARCHAR(255) NULL
	,[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[CreatedBy] VARCHAR(255) NULL
	,[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[ChangedBy] VARCHAR(255) NULL

)
GO 

ALTER TABLE Sph.Land
ADD [Path] GEOGRAPHY NULL

GO
ALTER TABLE Sph.Land
ADD [Wkt] VARCHAR(MAX) NULL

GO
ALTER TABLE Sph.Land
ADD [EncodedWkt] VARCHAR(MAX) NULL
