USE [Sph]
IF OBJECT_ID('Sph.EntityForm', 'U') IS NOT NULL
  DROP TABLE Sph.EntityForm
GO

CREATE TABLE Sph.EntityForm
(
	 [EntityFormId] INT PRIMARY KEY IDENTITY(1,1)
	,[Data] XML NOT NULL
	,[Name] VARCHAR(255) NOT NULL
	,[Route] VARCHAR(255) NOT NULL
	,[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[CreatedBy] VARCHAR(255) NULL
	,[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[ChangedBy] VARCHAR(255) NULL
)
GO 
