IF OBJECT_ID('Sph.EntityForm', 'U') IS NOT NULL
  DROP TABLE Sph.EntityForm
GO

CREATE TABLE [Sph].[EntityForm]
(
	 [EntityFormId] INT PRIMARY KEY IDENTITY(1,1)
	,[EntityDefinitionId] INT NOT NULL
	,[Json] VARCHAR(MAX) NOT NULL
	,[IsPublished] BIT NOT NULL
	,[IsAllowedNewItem] BIT NOT NULL
	,[IsDefault] BIT NOT NULL
	,[Name] VARCHAR(255) NOT NULL
	,[Route] VARCHAR(255) NOT NULL
	,[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[CreatedBy] VARCHAR(255) NULL
	,[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[ChangedBy] VARCHAR(255) NULL
)
GO 

ALTER TABLE [Sph].[EntityForm]
ADD [Json] VARCHAR(MAX) NULL

ALTER TABLE Sph.EntityForm
ADD [IsAllowedNewItem] BIT NOT NULL DEFAULT 0

GO 
/*
ALTER TABLE Sph.EntityForm
ADD [Entity] VARCHAR(255) NOT NULL DEFAULT ''
*/

