USE [Sph]
GO
 IF OBJECT_ID('Sph.Rebate', 'U') IS NOT NULL
  DROP TABLE Sph.Rebate
GO

CREATE TABLE [Sph].[Rebate](
	[RebateId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Amount] [decimal](18, 0) NOT NULL,
	[Data] XML NOT NULL	,
	[StartDate] SMALLDATETIME NULL,
	[EndDate] SMALLDATETIME NULL,
	[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE(),
	[CreatedBy] VARCHAR(255) NULL,
	[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE(),
	[ChangedBy] VARCHAR(255) NULL
	)
GO



