#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Bespoke.Sph.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/App/Views/QueryEndpointDesigner/_advanced.cshtml")]
    public partial class _Areas_App_Views_QueryEndpointDesigner__advanced_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_App_Views_QueryEndpointDesigner__advanced_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n<form");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n                <label>\r\n                    <input");

WriteLiteral(" data-bind=\"checked: allowQueryCache\"");

WriteLiteral(" id=\"allow-query-cached\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"allowQueryCache\"");

WriteLiteral("/>\r\n                    Allow generated query to be cached\r\n                </lab" +
"el>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    \r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" for=\"cache-filter-name\"");

WriteLiteral(" class=\"col-lg-3 col-md-3 control-label\"");

WriteLiteral(">How long </label>\r\n        <div");

WriteLiteral(" class=\"col-lg-9 col-md-9 col-sm-12\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"value: CacheFilter, enable: allowQueryCache\"");

WriteLiteral("\r\n                   required");

WriteLiteral(" pattern=\"^[0-9]{1,7}\"");

WriteLiteral("\r\n                   placeholder=\"In seconds\"");

WriteLiteral("\r\n                   class=\"form-control\"");

WriteLiteral(" id=\"cache-filter-name\"");

WriteLiteral(">\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" for=\"cache-profile\"");

WriteLiteral(" class=\"col-lg-3 control-label\"");

WriteLiteral(">Cache Control</label>\r\n        <div");

WriteLiteral(" class=\"col-lg-6\"");

WriteLiteral(">\r\n            <select");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"cache-profile\"");

WriteLiteral(" data-bind=\"value:CacheProfile, enable:allowQueryCache\"");

WriteLiteral(">\r\n                <option");

WriteLiteral(" value=\"\"");

WriteLiteral("></option>\r\n                <option");

WriteLiteral(" value=\"Public\"");

WriteLiteral(">Public</option>\r\n                <option");

WriteLiteral(" value=\"Private\"");

WriteLiteral(">Private</option>\r\n            </select>\r\n        </div>\r\n    </div>\r\n</form>\r\n");

        }
    }
}
#pragma warning restore 1591
