#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Views.Shared.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/CurrencyElement.cshtml")]
    public partial class CurrencyElement_ : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.CurrencyElement>
    {
        public CurrencyElement_()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
 if (string.IsNullOrWhiteSpace(Model.Enable))
{
    Model.Enable = "true";
}

            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
 if (Model.IsCompact)
{

            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteAttribute("class", Tuple.Create(" class=\"", 160), Tuple.Create("\"", 216)
            
            #line 8 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
, Tuple.Create(Tuple.Create("", 168), Tuple.Create<System.Object, System.Int32>(Model.CssClass + " form-control "+ Model.Size
            
            #line default
            #line hidden
, 168), false)
);

WriteAttribute("title", Tuple.Create("\r\n           title=\"", 217), Tuple.Create("\"", 251)
            
            #line 9 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
, Tuple.Create(Tuple.Create("", 237), Tuple.Create<System.Object, System.Int32>(Model.Tooltip
            
            #line default
            #line hidden
, 237), false)
);

WriteLiteral(" data-bind=\"");

            
            #line 9 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
                                         Write(Html.Raw(Model.GetKnockoutBindingExpression()));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create("\r\n           id=\"", 314), Tuple.Create("\"", 347)
            
            #line 10 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
, Tuple.Create(Tuple.Create("", 331), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 331), false)
);

WriteLiteral(" type=\"text\"");

WriteAttribute("name", Tuple.Create(" name=\"", 360), Tuple.Create("\"", 378)
            
            #line 10 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
, Tuple.Create(Tuple.Create("", 367), Tuple.Create<System.Object, System.Int32>(Model.Path
            
            #line default
            #line hidden
, 367), false)
);

WriteLiteral(" />\r\n");

            
            #line 11 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
}
else
{


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" data-bind=\"visible:");

            
            #line 15 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
                                          Write(Model.Visible);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n        <label");

WriteAttribute("for", Tuple.Create(" for=\"", 477), Tuple.Create("\"", 499)
            
            #line 16 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
, Tuple.Create(Tuple.Create("", 483), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 483), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 500), Tuple.Create("\"", 528)
            
            #line 16 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
, Tuple.Create(Tuple.Create("", 508), Tuple.Create<System.Object, System.Int32>(Model.LabelCssClass
            
            #line default
            #line hidden
, 508), false)
);

WriteLiteral(">");

            
            #line 16 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
                                                              Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 564), Tuple.Create("\"", 597)
            
            #line 17 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
, Tuple.Create(Tuple.Create("", 572), Tuple.Create<System.Object, System.Int32>(Model.InputPanelCssClass
            
            #line default
            #line hidden
, 572), false)
);

WriteLiteral(">\r\n            <input");

WriteAttribute("class", Tuple.Create("  class=\"", 619), Tuple.Create("\"", 676)
            
            #line 18 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
, Tuple.Create(Tuple.Create("", 628), Tuple.Create<System.Object, System.Int32>(Model.CssClass + " form-control "+ Model.Size
            
            #line default
            #line hidden
, 628), false)
);

WriteAttribute("title", Tuple.Create("\r\n                   title=\"", 677), Tuple.Create("\"", 719)
            
            #line 19 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
, Tuple.Create(Tuple.Create("", 705), Tuple.Create<System.Object, System.Int32>(Model.Tooltip
            
            #line default
            #line hidden
, 705), false)
);

WriteLiteral(" data-bind=\"");

            
            #line 19 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
                                                 Write(Html.Raw(Model.GetKnockoutBindingExpression()));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create("\r\n                   id=\"", 782), Tuple.Create("\"", 823)
            
            #line 20 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
, Tuple.Create(Tuple.Create("", 807), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 807), false)
);

WriteLiteral(" type=\"text\"");

WriteAttribute("name", Tuple.Create(" name=\"", 836), Tuple.Create("\"", 854)
            
            #line 20 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
, Tuple.Create(Tuple.Create("", 843), Tuple.Create<System.Object, System.Int32>(Model.Path
            
            #line default
            #line hidden
, 843), false)
);

WriteLiteral(" />\r\n        </div>\r\n");

            
            #line 22 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
        
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
         if (!string.IsNullOrWhiteSpace(Model.HelpText))
        {

            
            #line default
            #line hidden
WriteLiteral("            <span");

WriteLiteral(" class=\"help-block\"");

WriteLiteral(">");

            
            #line 24 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
                                Write(Model.HelpText);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 25 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 27 "..\..\Views\Shared\EditorTemplates\CurrencyElement.cshtml"
}
            
            #line default
            #line hidden
WriteLiteral("  ");

        }
    }
}
#pragma warning restore 1591
