#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Sph.Web.Views.Shared.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
    using Bespoke.Sph.Domain;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/EntityLookupElement.cshtml")]
    public partial class EntityLookupElement : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.EntityLookupElement>
    {
        public EntityLookupElement()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
  
    if (string.IsNullOrWhiteSpace(Model.Enable))
    {
        Model.Enable = "true";
    }
    
    var columns = string.Join(",", Model.LookupColumnCollection.Select(c => string.Format("'{0}'", c)));
    Console.WriteLine(columns);


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 14 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
 if (Model.IsCompact)
{


            
            #line default
            #line hidden
WriteLiteral("    <a class=\"btn btn-link\"\r\n       data-bind=\"tooltip :\'");


            
            #line 18 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                       Write(Model.Tooltip);

            
            #line default
            #line hidden
WriteLiteral("\',lookup : {entity: \'");


            
            #line 18 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                                                          Write(Model.Entity);

            
            #line default
            #line hidden
WriteLiteral("\', member : \'");


            
            #line 18 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                                                                                    Write(Model.ValueMemberPath);

            
            #line default
            #line hidden
WriteLiteral("\', value : ");


            
            #line 18 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                                                                                                                     Write(Model.Path.ConvertJavascriptObjectToFunction());

            
            #line default
            #line hidden
WriteLiteral(", columns : [");


            
            #line 18 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                                                                                                                                                                                 Write(Html.Raw(columns));

            
            #line default
            #line hidden
WriteLiteral("]}\"\r\n       id=\"");


            
            #line 19 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
      Write(Model.ElementId);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <!-- ko text: Mrn -->\r\n        <!-- /ko -->\r\n        <i class=\"fa fa-" +
"search\"></i>\r\n    </a>\r\n");


            
            #line 24 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div data-bind=\"visible:");


            
            #line 27 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                       Write(Model.Visible);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"form-group\">\r\n        <label for=\"");


            
            #line 28 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
               Write(Model.ElementId);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"");


            
            #line 28 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                                        Write(Model.LabelCssClass);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 28 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                                                              Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n    \r\n        \r\n\r\n        <div class=\"");


            
            #line 32 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
               Write(Model.InputPanelCssClass);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            <a class=\"btn btn-link\" \r\n               data-bind=\"tooltip :\'");


            
            #line 34 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                               Write(Model.Tooltip);

            
            #line default
            #line hidden
WriteLiteral("\',lookup : {entity: \'");


            
            #line 34 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                                                                  Write(Model.Entity);

            
            #line default
            #line hidden
WriteLiteral("\', member : \'");


            
            #line 34 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                                                                                            Write(Model.ValueMemberPath);

            
            #line default
            #line hidden
WriteLiteral("\', value : ");


            
            #line 34 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                                                                                                                             Write(Model.Path.ConvertJavascriptObjectToFunction());

            
            #line default
            #line hidden
WriteLiteral(", columns : [");


            
            #line 34 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                                                                                                                                                                                         Write(Html.Raw(columns));

            
            #line default
            #line hidden
WriteLiteral("]}\"\r\n               id=\"");


            
            #line 35 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
              Write(Model.ElementId);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");


            
            #line 36 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                 if (!string.IsNullOrWhiteSpace(Model.DisplayTemplate))
                {
                    
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
               Write(Html.Raw(Model.DisplayTemplate));

            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                                                    ;
                }
                else
                {


            
            #line default
            #line hidden
WriteLiteral("                <!-- ko text: ");


            
            #line 43 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                         Write(Model.DisplayMemberPath.ConvertJavascriptObjectToFunction());

            
            #line default
            #line hidden
WriteLiteral(" -->\r\n");



WriteLiteral("                <!-- /ko -->\r\n");


            
            #line 45 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <i class=\"fa fa-search\"></i>\r\n            </a>\r\n        </div>\r\n");


            
            #line 49 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
         if (!string.IsNullOrWhiteSpace(Model.HelpText))
        {

            
            #line default
            #line hidden
WriteLiteral("            <span class=\"help-block\">");


            
            #line 51 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
                                Write(Model.HelpText);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 52 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");


            
            #line 54 "..\..\Views\Shared\EditorTemplates\EntityLookupElement.cshtml"

}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
