#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/ImageElement.cshtml")]
    public partial class _Views_Shared_EditorTemplates_ImageElement_cshtml_ : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.ImageElement>
    {
        public _Views_Shared_EditorTemplates_ImageElement_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\EditorTemplates\ImageElement.cshtml"
  
    var path = $"'/sph/image/store/' + {this.Model.Path}()";
    var width = Model.Width.HasValue ? "width=\"" + Model.Width.Value + "\"": string.Empty;
    var height = Model.Height.HasValue ? "height=\"" + Model.Height.Value + "\"" : string.Empty;
    
    if (string.IsNullOrWhiteSpace(Model.Enable))
    {
        Model.Enable = "true";
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n");

            
            #line 15 "..\..\Views\Shared\EditorTemplates\ImageElement.cshtml"
 if (!Model.IsCompact)
{

            
            #line default
            #line hidden
WriteLiteral("    <label");

WriteLiteral(" data-i18n=\"");

            
            #line 17 "..\..\Views\Shared\EditorTemplates\ImageElement.cshtml"
                 Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("class", Tuple.Create(" class=\"", 470), Tuple.Create("\"", 509)
, Tuple.Create(Tuple.Create("", 478), Tuple.Create("col-md-", 478), true)
            
            #line 17 "..\..\Views\Shared\EditorTemplates\ImageElement.cshtml"
, Tuple.Create(Tuple.Create("", 485), Tuple.Create<System.Object, System.Int32>(Model.LabelColMd ?? 4
            
            #line default
            #line hidden
, 485), false)
);

WriteLiteral(">");

            
            #line 17 "..\..\Views\Shared\EditorTemplates\ImageElement.cshtml"
                                                                       Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

            
            #line 18 "..\..\Views\Shared\EditorTemplates\ImageElement.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<img");

WriteLiteral(" data-test=\"xxx\"");

WriteAttribute("alt", Tuple.Create(" alt=\"", 556), Tuple.Create("\"", 574)
            
            #line 19 "..\..\Views\Shared\EditorTemplates\ImageElement.cshtml"
, Tuple.Create(Tuple.Create("", 562), Tuple.Create<System.Object, System.Int32>(Model.Label
            
            #line default
            #line hidden
, 562), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 575), Tuple.Create("\"", 597)
            
            #line 19 "..\..\Views\Shared\EditorTemplates\ImageElement.cshtml"
, Tuple.Create(Tuple.Create("", 583), Tuple.Create<System.Object, System.Int32>(Model.Tooltip
            
            #line default
            #line hidden
, 583), false)
);

WriteLiteral(" ");

            
            #line 19 "..\..\Views\Shared\EditorTemplates\ImageElement.cshtml"
                                                          Write(Html.Raw(width));

            
            #line default
            #line hidden
WriteLiteral("   ");

            
            #line 19 "..\..\Views\Shared\EditorTemplates\ImageElement.cshtml"
                                                                             Write(Html.Raw(height));

            
            #line default
            #line hidden
WriteLiteral("  data-bind=\"attr : {\'src\':");

            
            #line 19 "..\..\Views\Shared\EditorTemplates\ImageElement.cshtml"
                                                                                                                         Write(Html.Raw(path));

            
            #line default
            #line hidden
WriteLiteral("}, visible:");

            
            #line 19 "..\..\Views\Shared\EditorTemplates\ImageElement.cshtml"
                                                                                                                                                   Write(Html.Raw(Model.Visible));

            
            #line default
            #line hidden
WriteLiteral("\" />");

        }
    }
}
#pragma warning restore 1591
