#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
    using Bespoke.Sph.Domain;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/NumberTextBox.cshtml")]
    public partial class _Views_Shared_EditorTemplates_NumberTextBox_cshtml_ : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.NumberTextBox>
    {
        public _Views_Shared_EditorTemplates_NumberTextBox_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
  
    var originalPath = Model.Path.ToEmptyString().Replace("().", ".");
    if (string.IsNullOrWhiteSpace(Model.Enable))
    {
        Model.Enable = "true";
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
 if (Model.IsCompact)
{

            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteAttribute("step", Tuple.Create(" step=\"", 279), Tuple.Create("\"", 297)
            
            #line 12 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 286), Tuple.Create<System.Object, System.Int32>(Model.Step
            
            #line default
            #line hidden
, 286), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 298), Tuple.Create("\"", 354)
            
            #line 12 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 306), Tuple.Create<System.Object, System.Int32>(Model.CssClass + " form-control "+ Model.Size
            
            #line default
            #line hidden
, 306), false)
);

WriteAttribute("title", Tuple.Create("\r\n           title=\"", 355), Tuple.Create("\"", 389)
            
            #line 13 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 375), Tuple.Create<System.Object, System.Int32>(Model.Tooltip
            
            #line default
            #line hidden
, 375), false)
);

WriteLiteral(" data-bind=\"");

            
            #line 13 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
                                         Write(Html.Raw(Model.GetKnockoutBindingExpression()));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create("\r\n           id=\"", 452), Tuple.Create("\"", 485)
            
            #line 14 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 469), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 469), false)
);

WriteLiteral(" type=\"number\"");

WriteAttribute("name", Tuple.Create(" name=\"", 500), Tuple.Create("\"", 520)
            
            #line 14 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 507), Tuple.Create<System.Object, System.Int32>(originalPath
            
            #line default
            #line hidden
, 507), false)
);

WriteLiteral(" />\r\n");

            
            #line 15 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
}
else
{


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" data-bind=\"visible:");

            
            #line 19 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
                                          Write(Model.Visible);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" data-i18n=\"");

            
            #line 20 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
                     Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("for", Tuple.Create(" for=\"", 644), Tuple.Create("\"", 666)
            
            #line 20 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 650), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 650), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 667), Tuple.Create("\"", 695)
            
            #line 20 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 675), Tuple.Create<System.Object, System.Int32>(Model.LabelCssClass
            
            #line default
            #line hidden
, 675), false)
);

WriteLiteral(">");

            
            #line 20 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
                                                                                       Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 731), Tuple.Create("\"", 764)
            
            #line 21 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 739), Tuple.Create<System.Object, System.Int32>(Model.InputPanelCssClass
            
            #line default
            #line hidden
, 739), false)
);

WriteLiteral(">\r\n            <input");

WriteAttribute("step", Tuple.Create(" step=\"", 786), Tuple.Create("\"", 804)
            
            #line 22 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 793), Tuple.Create<System.Object, System.Int32>(Model.Step
            
            #line default
            #line hidden
, 793), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 805), Tuple.Create("\"", 861)
            
            #line 22 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 813), Tuple.Create<System.Object, System.Int32>(Model.CssClass + " form-control "+ Model.Size
            
            #line default
            #line hidden
, 813), false)
);

WriteAttribute("title", Tuple.Create("\r\n                   title=\"", 862), Tuple.Create("\"", 904)
            
            #line 23 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 890), Tuple.Create<System.Object, System.Int32>(Model.Tooltip
            
            #line default
            #line hidden
, 890), false)
);

WriteLiteral(" data-bind=\"");

            
            #line 23 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
                                                 Write(Html.Raw(Model.GetKnockoutBindingExpression()));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create("\r\n                   id=\"", 967), Tuple.Create("\"", 1008)
            
            #line 24 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 992), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 992), false)
);

WriteLiteral(" type=\"number\"");

WriteAttribute("name", Tuple.Create(" name=\"", 1023), Tuple.Create("\"", 1043)
            
            #line 24 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 1030), Tuple.Create<System.Object, System.Int32>(originalPath
            
            #line default
            #line hidden
, 1030), false)
);

WriteLiteral(" />\r\n        </div>\r\n");

            
            #line 26 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
        
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
         if (!string.IsNullOrWhiteSpace(Model.HelpText))
        {

            
            #line default
            #line hidden
WriteLiteral("            <span");

WriteLiteral(" class=\"help-block\"");

WriteLiteral(">");

            
            #line 28 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
                                Write(Model.HelpText);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 29 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 31 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
}
            
            #line default
            #line hidden
WriteLiteral("  ");

        }
    }
}
#pragma warning restore 1591
