#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/NumberTextBox.cshtml")]
    public partial class _Views_Shared_EditorTemplates_NumberTextBox_cshtml_ : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.NumberTextBox>
    {
        public _Views_Shared_EditorTemplates_NumberTextBox_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
 if (string.IsNullOrWhiteSpace(Model.Enable))
{
    Model.Enable = "true";
}

            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
 if (Model.IsCompact)
{

            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteAttribute("step", Tuple.Create(" step=\"", 158), Tuple.Create("\"", 176)
            
            #line 8 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 165), Tuple.Create<System.Object, System.Int32>(Model.Step
            
            #line default
            #line hidden
, 165), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 177), Tuple.Create("\"", 233)
            
            #line 8 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 185), Tuple.Create<System.Object, System.Int32>(Model.CssClass + " form-control "+ Model.Size
            
            #line default
            #line hidden
, 185), false)
);

WriteAttribute("title", Tuple.Create("\r\n           title=\"", 234), Tuple.Create("\"", 268)
            
            #line 9 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 254), Tuple.Create<System.Object, System.Int32>(Model.Tooltip
            
            #line default
            #line hidden
, 254), false)
);

WriteLiteral(" data-bind=\"");

            
            #line 9 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
                                         Write(Html.Raw(Model.GetKnockoutBindingExpression()));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create("\r\n           id=\"", 331), Tuple.Create("\"", 364)
            
            #line 10 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 348), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 348), false)
);

WriteLiteral(" type=\"number\"");

WriteAttribute("name", Tuple.Create(" name=\"", 379), Tuple.Create("\"", 397)
            
            #line 10 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 386), Tuple.Create<System.Object, System.Int32>(Model.Path
            
            #line default
            #line hidden
, 386), false)
);

WriteLiteral(" />\r\n");

            
            #line 11 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
}
else
{


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" data-bind=\"visible:");

            
            #line 15 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
                                          Write(Model.Visible);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" data-i18n=\"");

            
            #line 16 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
                     Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("data-i18n=\"");

            
            #line 16 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
                                             Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("for", Tuple.Create(" for=\"", 545), Tuple.Create("\"", 567)
            
            #line 16 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 551), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 551), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 568), Tuple.Create("\"", 596)
            
            #line 16 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
               , Tuple.Create(Tuple.Create("", 576), Tuple.Create<System.Object, System.Int32>(Model.LabelCssClass
            
            #line default
            #line hidden
, 576), false)
);

WriteLiteral(">");

            
            #line 16 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
                                                                                                               Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 632), Tuple.Create("\"", 665)
            
            #line 17 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 640), Tuple.Create<System.Object, System.Int32>(Model.InputPanelCssClass
            
            #line default
            #line hidden
, 640), false)
);

WriteLiteral(">\r\n            <input");

WriteAttribute("step", Tuple.Create(" step=\"", 687), Tuple.Create("\"", 705)
            
            #line 18 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 694), Tuple.Create<System.Object, System.Int32>(Model.Step
            
            #line default
            #line hidden
, 694), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 706), Tuple.Create("\"", 762)
            
            #line 18 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 714), Tuple.Create<System.Object, System.Int32>(Model.CssClass + " form-control "+ Model.Size
            
            #line default
            #line hidden
, 714), false)
);

WriteAttribute("title", Tuple.Create("\r\n                   title=\"", 763), Tuple.Create("\"", 805)
            
            #line 19 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 791), Tuple.Create<System.Object, System.Int32>(Model.Tooltip
            
            #line default
            #line hidden
, 791), false)
);

WriteLiteral(" data-bind=\"");

            
            #line 19 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
                                                 Write(Html.Raw(Model.GetKnockoutBindingExpression()));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create("\r\n                   id=\"", 868), Tuple.Create("\"", 909)
            
            #line 20 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 893), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 893), false)
);

WriteLiteral(" type=\"number\"");

WriteAttribute("name", Tuple.Create(" name=\"", 924), Tuple.Create("\"", 942)
            
            #line 20 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
, Tuple.Create(Tuple.Create("", 931), Tuple.Create<System.Object, System.Int32>(Model.Path
            
            #line default
            #line hidden
, 931), false)
);

WriteLiteral(" />\r\n        </div>\r\n");

            
            #line 22 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
        
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
         if (!string.IsNullOrWhiteSpace(Model.HelpText))
        {

            
            #line default
            #line hidden
WriteLiteral("            <span");

WriteLiteral(" class=\"help-block\"");

WriteLiteral(">");

            
            #line 24 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
                                Write(Model.HelpText);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 25 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 27 "..\..\Views\Shared\EditorTemplates\NumberTextBox.cshtml"
}
            
            #line default
            #line hidden
WriteLiteral("  ");

        }
    }
}
#pragma warning restore 1591
