#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
    using Bespoke.Sph.Domain;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/TextAreaElement.cshtml")]
    public partial class _Views_Shared_EditorTemplates_TextAreaElement_cshtml_ : System.Web.Mvc.WebViewPage<Bespoke.Sph.Domain.TextAreaElement>
    {
        public _Views_Shared_EditorTemplates_TextAreaElement_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
  
    var originalPath = Model.Path.ToEmptyString().Replace("().", ".");
    if (string.IsNullOrWhiteSpace(Model.Enable))
    {
        Model.Enable = "true";
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
 if (Model.IsCompact)
{


            
            #line default
            #line hidden
WriteLiteral("    <textarea");

WriteAttribute("class", Tuple.Create(" class=\"", 286), Tuple.Create("\"", 342)
            
            #line 13 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
, Tuple.Create(Tuple.Create("", 294), Tuple.Create<System.Object, System.Int32>(Model.CssClass + " form-control "+ Model.Size
            
            #line default
            #line hidden
, 294), false)
);

WriteAttribute("title", Tuple.Create("\r\n              title=\"", 343), Tuple.Create("\"", 380)
            
            #line 14 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
, Tuple.Create(Tuple.Create("", 366), Tuple.Create<System.Object, System.Int32>(Model.Tooltip
            
            #line default
            #line hidden
, 366), false)
);

WriteLiteral(" data-bind=\"");

            
            #line 14 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
                                            Write(Html.Raw(Model.GetKnockoutBindingExpression()));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create("\r\n              id=\"", 443), Tuple.Create("\"", 479)
            
            #line 15 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
, Tuple.Create(Tuple.Create("", 463), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 463), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 480), Tuple.Create("\"", 500)
            
            #line 15 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
, Tuple.Create(Tuple.Create("", 487), Tuple.Create<System.Object, System.Int32>(originalPath
            
            #line default
            #line hidden
, 487), false)
);

WriteLiteral("></textarea>\r\n");

            
            #line 16 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
}
else
{


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" data-bind=\"visible:");

            
            #line 20 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
                                          Write(Html.Raw(Model.Visible));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" data-i18n=\"");

            
            #line 21 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
                     Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("for", Tuple.Create(" for=\"", 643), Tuple.Create("\"", 665)
            
            #line 21 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
, Tuple.Create(Tuple.Create("", 649), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 649), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 666), Tuple.Create("\"", 694)
            
            #line 21 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
, Tuple.Create(Tuple.Create("", 674), Tuple.Create<System.Object, System.Int32>(Model.LabelCssClass
            
            #line default
            #line hidden
, 674), false)
);

WriteLiteral(">");

            
            #line 21 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
                                                                                       Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 730), Tuple.Create("\"", 763)
            
            #line 22 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
, Tuple.Create(Tuple.Create("", 738), Tuple.Create<System.Object, System.Int32>(Model.InputPanelCssClass
            
            #line default
            #line hidden
, 738), false)
);

WriteLiteral(">\r\n            <textarea");

WriteAttribute("class", Tuple.Create(" class=\"", 788), Tuple.Create("\"", 844)
            
            #line 23 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
, Tuple.Create(Tuple.Create("", 796), Tuple.Create<System.Object, System.Int32>(Model.CssClass + " form-control "+ Model.Size
            
            #line default
            #line hidden
, 796), false)
);

WriteAttribute("title", Tuple.Create("\r\n                      title=\"", 845), Tuple.Create("\"", 890)
            
            #line 24 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
, Tuple.Create(Tuple.Create("", 876), Tuple.Create<System.Object, System.Int32>(Model.Tooltip
            
            #line default
            #line hidden
, 876), false)
);

WriteLiteral(" data-bind=\"");

            
            #line 24 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
                                                    Write(Html.Raw(Model.GetKnockoutBindingExpression()));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create("\r\n                      id=\"", 953), Tuple.Create("\"", 997)
            
            #line 25 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
, Tuple.Create(Tuple.Create("", 981), Tuple.Create<System.Object, System.Int32>(Model.ElementId
            
            #line default
            #line hidden
, 981), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 998), Tuple.Create("\"", 1018)
            
            #line 25 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"
, Tuple.Create(Tuple.Create("", 1005), Tuple.Create<System.Object, System.Int32>(originalPath
            
            #line default
            #line hidden
, 1005), false)
);

WriteLiteral("></textarea>\r\n        </div>\r\n    </div>\r\n");

            
            #line 28 "..\..\Views\Shared\EditorTemplates\TextAreaElement.cshtml"

}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
